### ISSUE TITLE
Migrate to Swarmkit

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#100]
The migration from the container based swarm to Swarmkit should give use
* more stability (see #99)
* a better support for enhancements like #97 

@yamalight Could you please figure out what we have to do to prepare a migration?

**Comment by yamalight** [comment]
@MichaelRoeder The way I see it, the following steps should do it:

1. Gather all used docker functions in current codebase (from quick search it seems to be: `pull`, `network create`, `container create`, `container start`, `network add container` and `list container`)
2. Find analogues in swarm mode (from quick glance at API, latest version should have all we need)
3. Migrate code and tests (tests would probably take most time, from what I've seen usage within code is quite limited)
4. Test with local swarm with 1 node (e.g. useful for local deployments)
5. Test with local swarm with 2-3 nodes
6. Once everything works - tear down old swarm, reconfigure new swarm on our server and re-deploy new version (that would probably mean ~1 day of downtime for system)

Changing code itself would probably be the easiest thing here.

**Comment by MichaelRoeder** [comment]
That means that Docker swarm or Swarmkit will become a prerequesite to run the HOBBIT platform, right?

**Comment by yamalight** [comment]
@MichaelRoeder swarmkit will, but it's been integrated into docker for quite some time

**Comment by denkv** [comment]
Docker networks would need to be overlay ones:

```
docker network remove hobbit
docker network remove hobbit-core
docker network create --driver overlay hobbit
docker network create --driver overlay hobbit-core
```

**Comment by MichaelRoeder** [comment]
This is not possible in a local setup, is it?

**Comment by yamalight** [comment]
I think you can have one-node swarm and overlay network on it, so should work locally too.

**Comment by MichaelRoeder** [comment]
Sure but wouldn't that create additional effort for the user?
I do not really see why we now have to care about the type of the network. Before, we could work with the networks regardless of their type, right?

**Comment by yamalight** [comment]
`docker swarm init && docker create network --driver overlay hobbit` is not that much effort IMO :P

**Comment by MichaelRoeder** [comment]
I simply don't know how good swarm is now intergrated into Docker. If the user has to take care of adding stuff like `docker-compose -H :4000` as we have to do it now, I would try to avoid this ;)

Apart from that, I still haven't got an answer why this should be necessary.

**Comment by denkv** [comment]
That's necessary because docker services use overlay networks instead of regular ones, more info: https://docs.docker.com/engine/swarm/networking/

Such network setup would be the default because as currently planned platform will only work with swarm.

In a local setup swarm is being initialized as just `docker swarm init` without any other dependencies.

**Comment by yamalight** [comment]
New swarm just has different CLI commands, no need to specify different endpoint AFAIK.

**Comment by denkv** [comment]
`ContainerManager::createContainer` would be removed as it's only used once in `startContainer` (except for tests) and such an action is probably not possible with new swarm.
