### ISSUE TITLE
Provide pre-built docker images for docker-compose.yml

### ISSUE THREAD

**Issue by yamalight** [hobbit-project/platform#106]
We need to provide pre-build images for docker-compose.yml.
This can be done with following steps:

1. Convert all Dockerfiles to multi-stage ones with builds done inside of them (and remove no longer needed makefiles)
2. Setup autobuilds of components on Docker Hub (each component should use a tag, e.g. `hobbit/platform:ui`, versions / branches can be optionally appended)
3. Change `docker-compose.yml` to use new images

**Comment by yamalight** [comment]
I've set up a basic org on hub here: https://hub.docker.com/u/hobbitproject/

**Comment by MichaelRoeder** [comment]
I used our own gitlab until now, but using the official docker hub might be even better.
Can you add the credentials to our wiki in the https://git.informatik.uni-leipzig.de/hobbit/platform/ ?

**Comment by MichaelRoeder** [comment]
1. Don't we need the makefiles for our local development?
2. Sounds very nice :smiley: 
3. We already use something like that for our server. Where should we put it? Should it replace our current compose file in the project?

**Comment by yamalight** [comment]
1. yes, because you want to build local changes
2. 👍 
3. I'd say compose file should pull existing images instead of building ones locally once we set this up

**Comment by MichaelRoeder** [comment]
fixed.
