### ISSUE TITLE
Fix user account problem

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#115]
## Problem

Keycloak offers to set a user account name which is used for logging in to the platform. However, gitlab is relying on the e-mail address only (i.e., on its first part like `max.power` of `max.power@example.org`). We tried to tackle the problem by defining a [clear guideline](https://github.com/hobbit-project/platform/wiki/User-registration) for the users in our wiki.

However, a remaining problem is that the most users are not reading the guideline but are simply registering themself as for other services, i.e., they freely choose a user name. This leads to problems when they try to benchmark a system that they have uploaded. They can not see it in the GUI because we only show systems of the user (which have the user name in their URL).

## Discussion

Since a guideline does not work, we need to tackle this problem in a different way. I could imagine different approaches (the order is random and does not imply a weighting) and I would be happy to have a discussion regarding this.

1. **Adapt registration.** We could try to adapt the registration process in keycloak to make sure that the user name can not be chosen but is determined based on the mail address.
1. **Extend the user information known by the GUI.** If the GUI knows the mail address of the user, it could use the first part to check the URLs of systems.
1. **Get user rights from gitlab.** Instead of relying on the URL of a system, it should be possible to use Gitlabs API to derive whether a given user can "see" a project and its containers. This would enable the users to define whether other users can benchmark their systems by using the visibility feature of gitlab projects. Additionally, it would enable the usage of project groups/teams in gitlab.

Feel free to comment the approaches or present additional ways.

**Comment by yamalight** [comment]
@MichaelRoeder looks like you can just toggle username editing, see: http://www.keycloak.org/docs/3.3/server_admin/topics/users/user-registration.html
Have you tried that?

**Comment by MichaelRoeder** [comment]
Thanks for that hint. Will try it.

**Comment by MichaelRoeder** [comment]
Adaptations of the registration are possible but need additional effort (http://www.keycloak.org/docs/3.3/server_development/topics/custom-attributes.html). However, our version of Keycloak offers the usage of the e-mail as user name.
![keycloak admin console 3](https://user-images.githubusercontent.com/6122307/30479616-56c58880-9a16-11e7-9d67-709ecfd0c500.png)

This does not exactly solve the problem, since we would end up with users like the following
![keycloak admin console 2](https://user-images.githubusercontent.com/6122307/30479622-5d8ff07e-9a16-11e7-96f5-2f483c3f82ea.png)

However, we could update the backend to use only the first part of the user name to check the URL of a system.

**Comment by denkv** [comment]
Relying on local-part of email addresses can lead to problems when encountering users with the same local-part but different domains (`john@example1` and `john@example2`). If it's possible, we should integrate with gitlab there IMO.

**Comment by MichaelRoeder** [comment]
### Fix description

The implementation uses the Gitlab API to get a list of projects that are visible for a given user. That made it necessary to distinguish two different cases.
1. The platform is authenticated as a Gitlab user with admin rights. In this case, a given user is identified using its mail address which the GUI gets from Keycloak and which is the same in both systems (Keycloak and Gitlab). The controller is requesting the list of projects that are owned by the given user from the Gitlab API and adds all public and internal projects (since the user can see them as well). If a user can ont be identified via its mail, only public and internal projects are returned.
2. The platform uses the Gitlab API with a user without admin rights. That means that the retrieval of projects seen by a given user is also influenced by the rights of the API user. Additionally, it is possible that (especially in a local deployment of a platform) the user authenticated in a local Keycloak can not be found in the online Gitlab. Thus, the platform always returns all projects that can be seen by the Gitlab API user.

The GUI makes sure that a guest does not even get the public systems (otherwise they could start an experiment with them)

### Drawbacks

Note that the current implementation does not support
a) sharing of projects (i.e., a project owned by user A is not visible for user B even if A invited him into the project),
b) user groups / organisations.

These features have a much lower priority and will cause additional effort in the backend. They are further discussed in #132.

This issue will be closed as soon as the solution has been merged into the master.
