### ISSUE TITLE
Logout is not working anymore

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#118]
## Problem

When logged in as "Anonymous Guest", the logout button is not working correctly. Instead of being redirected to the login page of Keycloak the user is redirected to the main page of the GUI still logged in as "Anonymous Guest".

**Comment by MichaelRoeder** [comment]
It looks like the users browser is correctly requesting the authentication URL, e.g.,
```
https://keycloak.project-hobbit.eu/auth/realms/Hobbit/protocol/openid-connect/auth?client_id=Hobbit-GUI&redirect_uri=http%3A%2F%2Fmaster.project-hobbit.eu%2F%23&state=2f07e22e-3ab7-4eb4-8190-cde704e30a5c&nonce=ce739288-0b7e-4cb5-9ff8-49b9c05725d2&response_mode=fragment&response_type=code&scope=openid
```
However, Keycloak is simply forwarding the user back to the platform UI.

I would assume that a check of the logout mechanism that should "stop" the session of the user is needed since the other behaviour of the UI looks correct so far.

The problem occurs with "normal" user accounts as well. AFAIK this was working correctly in former versions of the platform.

**Comment by Ennosigaeon** [comment]
This issue was introduced by #81. A fix is available in branch _fix-issue-118_.

**Comment by MichaelRoeder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[HOBBIT] Github issues](https://trello.com/c/kx7aoZth/397-hobbit-github-issues)
