### ISSUE TITLE
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here

### ISSUE THREAD

**Issue by kiat** [hobbit-project/platform#12]
When I run the docker-compise build 

I get this error. 

`platform$ docker-compose build
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in "./docker-compose.yml", line 4, column 22
`

Do you know what the problem is?

Thanks

**Comment by MichaelRoeder** [comment]
Thanks for reporting the problem. Please checkout the latest commit to the master branch and try it again.

**Comment by wi-ski** [comment]
im getting this too

**Comment by MichaelRoeder** [comment]
Is it exactly the same line/column? Which version of Docker and Docker-compose do you use?
