### ISSUE TITLE
Separation of running and finished challenges

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#123]
The current implementation shows all challenges in the same table. By default the challenges are sorted by their name.

Although this is already a good state we could further improve the usability of this page by separating the page into two areas. 
1. The upper area could have the headline "Currently running challenges" (or similar) and contains a table that has only the challenges that are running at the moment. They should have a default sorting (e.g., name or date).
2. The lower area contains closed challenges. This table should be sorted using the execution date of the challenge with the latest challenge as the first element.

This would give us the following advantages:
* It is easier for a user to participate in a challenge since he can easily distinguish between challenges that are still open and older, closed challenges.
* It is easier for a user to access the results of a challenge that has been carried out lately (since the sorting of the second challenge ranks the latest challenges higher). The chance that an older challenge is accessed via this page (and not directly via a link) is lower (from my point of view). However, it would still be possible since the user can still sort the lower table and search for the challenge he is interested in.

@romankorf @Ennosigaeon What do you think?

**Comment by Ennosigaeon** [comment]
I have implemented your suggested solution
