### ISSUE TITLE
With new UI there is now no URLs for some pages

### ISSUE THREAD

**Issue by denkv** [hobbit-project/platform#137]
Missing URL for "experiments of task for challenge" (URL does not change when navigating to that).

Same with similar page for leaderboards.

**Comment by Ennosigaeon** [comment]
So, just to be sure: You expect the URL to change if the experiments of a task are listed, e.g. change `challenges/http:%2F%2Fw3id.org%2Fhobbit%2Fchallenges%2304da2c2e-5337-49fb-85d7-053aa2657b81/experiments` to `challenges/http:%2F%2Fw3id.org%2Fhobbit%2Fchallenges%2304da2c2e-5337-49fb-85d7-053aa2657b81/experiments/http%3A%2F%2Fw3id.org%2Fhobbit%2Fchallenges%2304da2c2e-5337-49fb-85d7-053aa2657b81_task2` but the page behaviour should stay the same?

**Comment by denkv** [comment]
The current page behaviour is right. We just need to be able to link to specific pages.

**Comment by denkv** [comment]
Minor problem: when navigating to (or reloading) the page like "experiments of task", the selected task is not highlighted in the task list.

**Comment by Ennosigaeon** [comment]
Should work now.
