### ISSUE TITLE
Access to logs

### ISSUE THREAD

**Issue by smirnp** [hobbit-project/platform#148]
I would like to clarify/discuss about the meaning of logs for the platform users.
Browsing logs (at least from benchmark and system containers) will greatly save users' time during integration their systems/benchmarks into the online platform.

I saw some kibana interface, but haven't found any information about it except some private documentation. 

Do platform users freely allowed to see all logs of the online platform? 
May such an opportunity being introduced to challenge participants?
May be it makes sense to restrict users only with their container's logs?

**Comment by MichaelRoeder** [comment]
> Do platform users freely allowed to see all logs of the online platform?

No. In general, we want to allow people to benchmark their system without forcing them to show the content of their system to others. This includes the logs a system produces. Giving all platform users a general access to all logs would decrease this kind of "privacy".

> May such an opportunity being introduced to challenge participants?

The solution we want to implement regarding logs will not be bound to challenges

> May be it makes sense to restrict users only with their container's logs?

Exactly that is what we would like to do with #93

**Comment by Ennosigaeon** [comment]
Closing as #93 has been merged.
