### ISSUE TITLE
Caching problem

### ISSUE THREAD

**Issue by mirkospasic** [hobbit-project/platform#153]
When the experiment is finished, I cannot see it in the list of results for a long time, but if I disable caching, it will be there immediately. The webpage should be able to send a header that disables a long term caching.

**Comment by Ennosigaeon** [comment]
The result list is loaded via ajax which is not cached (verified with Firefox and Chrome with response code 200). However, during my tests I have noticed that an experiment only shows up in the results when the experiment has finished. You can test this by opening `/experiments/<ID>`. As long as this page shows `Could not find results for this experiments. Either the experiment has not been finished or it does not exist.` the `<ID>` does not show up in the result list.´

So my guess is, that while you were disabling your cache, the experiment finished and showed up in the result list on page reload.

@MichaelRoeder Maybe it would be more intuitive to list experiments in the result list as soon as they are submitted.

**Comment by MichaelRoeder** [comment]
I checked it together with @mirkospasic. The experiment was done and I could see it but Mirko could not. Only disabling the cache made it visible for him.

**Comment by mirkospasic** [comment]
It is definitely cached. Not only the list of results, but also the status of current experiments.

I started the experiment, and the list of running experiments was empty, and the waiting queue as well. After clearing the cache in browser, everything was up-to-date. I have tried Firefox and Chrome from Ubuntu, and my phone browser, as well, and the behaviour is the same.

This issue only affects one of our local deployments of the platform. With my local deployment, and with master.hobbit-project I don't have this issue.

**Comment by Ennosigaeon** [comment]
Can you please also check whats the response code of the according requests. So for the experiment result list the request is called `query`

![unbenannt](https://user-images.githubusercontent.com/7460134/32785446-db210018-c951-11e7-92b7-92d8fed7194b.PNG)

and for the result status it is called `status`. The response code should be 200. If you see 304 the results are cached by the browser, if the response code is 200, the results are somehow cached by the plattform.

**Comment by mirkospasic** [comment]
Status is: 200 OK, but next time, it says: 200 OK (from disk cache)

**Comment by yamalight** [comment]
According to screenshot, server sends [Access-Control-Max-Age](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Max-Age) headers that is equal to 3600 seconds. This is most likely what you need to tweak to fix this.

**Comment by Ennosigaeon** [comment]
I have added `Cache-Control: no-cache` header to all jetty rest endpoints.  @mirkospasic  Please check if the problem still persists.

**Comment by mirkospasic** [comment]
What do I have to do/update/build to check the new fix? @Ennosigaeon

**Comment by MichaelRoeder** [comment]
You have to checkout the [`153_disable_cache`](https://github.com/hobbit-project/platform/compare/153_disable_cache) branch and rebuild the platform (run `make` and `docker-compose -f <your-compose-file> build`)

**Comment by mirkospasic** [comment]
I have checked. It is very non-deterministic. Sometimes it happens, sometime it doesn't. :-( Is it maybe possible to have caching somewhere between server and client, as I'm accessing the server with deployed platform through the other server?

**Comment by mirkospasic** [comment]
For example, if I use Firefox as usual, the caching will appear, but if I use it with this kind of developer tool (Inspect Element -> Network tab), the caching won't be there.

**Comment by yamalight** [comment]
Having just `Cache-Control` header might no be enough for some browsers, see [this answer](https://stackoverflow.com/a/2068407) for details. Might want to test it with all 3 headers

**Comment by mirkospasic** [comment]
I have tested this issue with Firefox and Chrome from Ubuntu.

**Comment by Ennosigaeon** [comment]
Ok, another try. I have added the additional headers suggested by @yamalight. Changes are again available in [153_disable_cache](https://github.com/hobbit-project/platform/compare/153_disable_cache). Please try again, if the problem still persists...

**Comment by mirkospasic** [comment]
I have checked, and everything is the same. :-(

**Comment by mirkospasic** [comment]
Maybe this is not any more relevant. I found a problem. On our local deployment, we access platform through the other server and nginx on it. It contained a problematic configuration. Now, we disabled all expire headers, and now it works as it should. Can I close the issue?

**Comment by MichaelRoeder** [comment]
If you can not reproduce the problem anymore after your changes you can close it.
