### ISSUE TITLE
URL to experiment result is not working

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#155]
## Problem
When creating a new experiment, the GUI shows a link to the result page of this experiment. 
![hobbit gui 11](https://user-images.githubusercontent.com/6122307/32776059-a484d2e8-c931-11e7-978e-ee9acef4831d.png)

However, the link (e.g., http://localhost:8080/experiments/details?id=1510656190751) is not working correctly since the page always shows the following error message even if the experiment is done.
![hobbit gui 12](https://user-images.githubusercontent.com/6122307/32776158-f2749eca-c931-11e7-855b-75378778a782.png)

The experiment result overview uses a different URL for the experiment page (e.g., http://localhost:8080/experiments/1510656190751) which shows the correct results.
![hobbit gui 13](https://user-images.githubusercontent.com/6122307/32776270-4a7a531c-c932-11e7-98b5-3b37820241c9.png)

Either the `/details?id=` page has to be working or it should be replaced everywhere.

**Comment by Ennosigaeon** [comment]
I will fix that.

**Comment by denkv** [comment]
URLs should never change, and if they change anyway, you need to support every old one indefinitely.

I've added support for `/experiments/details?id=` and `/experiments/details?challenge-task-id` in that branch.

**Comment by denkv** [comment]
Hovewer it seems that old URL for experiments of challenge task didn't even work before. `#` in task URI value is mangled somewhere so you can't even reload the page (on `v1.0.12`).
