### ISSUE TITLE
Accessing FPT server via HTTP

### ISSUE THREAD

**Issue by mirkospasic** [hobbit-project/platform#156]
My components cannot access the dataset files via HTTP stored on the FTP server (e.g. http://hobbitdata.informatik.uni-leipzig.de/MOCHA_OC/T2/sf1/substitution_parameters/query_1_param.txt). It only happens at platform deployment at master.project-hobbit.eu, elsewhere this works. It started to happen recently (a couple of weeks ago).

**Comment by MichaelRoeder** [comment]
This is a problem of the cluster configuration.

**Comment by MichaelRoeder** [comment]
@yamalight identified https://github.com/moby/moby/issues/19474 as the root cause of this problem. 

The handling of DNS resolution has been changed within Docker and our solution to define a routing from the workers to the data node using `/etc/hosts` files does not work anymore.

**Comment by MichaelRoeder** [comment]
We reconfigured the single nodes. The problem should be fixed now.
@mirkospasic please check whether the problem is gone for you as well.

**Comment by mirkospasic** [comment]
@MichaelRoeder I have checked, and it worked... For the first time, but right now, the issue is present, again... :-(

**Comment by mirkospasic** [comment]
I can access this server using that name from time to time, but not always...

**Comment by MichaelRoeder** [comment]
It should be working now. Can you please check it again?

**Comment by mirkospasic** [comment]
I have tested it 3 times, and it should be working. I will close the issue. Thank you!
