### ISSUE TITLE
Keycloak image fails to start after VM crash

### ISSUE THREAD

**Issue by smirnp** [hobbit-project/platform#157]
I had a crash of my VM, then rebooted and keycloak started failing to start
May be some problems in its image taken from github? Where keyloak-jboss configuration is located?

I have faced the problem couple weeks ago, but later it was gone somehow (I have tried to manually install/run jboss, jetty). 

Now it appeared again. 

doing: sudo docker-compose up keycloak. The docker-compose.xml is default.

Here is the output:
`keycloak               | 17:17:22,058 INFO  [org.keycloak.services] (ServerService Thread Pool -- 54) KC-SERVICES0001: Loading config from standalone.xml or domain.xml
keycloak               | 17:17:23,005 WARN  [org.jboss.jca.core.connectionmanager.pool.strategy.OnePool] (ServerService Thread Pool -- 54) IJ000604: Throwable while attempting to get a new connection: null: javax.resource.ResourceException: IJ031084: Unable to create connection
keycloak               |        at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:343)
keycloak               |        at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.getLocalManagedConnection(LocalManagedConnectionFactory.java:350)
keycloak               |        at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createManagedConnection(LocalManagedConnectionFactory.java:285)
keycloak               |        at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreConcurrentLinkedDequeManagedConnectionPool.createConnectionEventListener(SemaphoreConcurrentLinkedDequeManagedConnectionPool.java:1319)
keycloak               |        at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreConcurrentLinkedDequeManagedConnectionPool.getConnection(SemaphoreConcurrentLinkedDequeManagedConnectionPool.java:496)
keycloak               |        at org.jboss.jca.core.connectionmanager.pool.AbstractPool.getSimpleConnection(AbstractPool.java:626)
keycloak               |        at org.jboss.jca.core.connectionmanager.pool.AbstractPool.getConnection(AbstractPool.java:598)
keycloak               |        at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.getManagedConnection(AbstractConnectionManager.java:590)
keycloak               |        at org.jboss.jca.core.connectionmanager.tx.TxConnectionManagerImpl.getManagedConnection(TxConnectionManagerImpl.java:429)
keycloak               |        at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.allocateConnection(AbstractConnectionManager.java:747)
keycloak               |        at org.jboss.jca.adapters.jdbc.WrapperDataSource.getConnection(WrapperDataSource.java:138)
keycloak               |        at org.jboss.as.connector.subsystems.datasources.WildFlyDataSource.getConnection(WildFlyDataSource.java:66)
keycloak               |        at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.getConnection(DefaultJpaConnectionProviderFactory.java:367)
keycloak               |        at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.lazyInit(LiquibaseDBLockProvider.java:65)
keycloak               |        at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.lambda$waitForLock$0(LiquibaseDBLockProvider.java:97)
keycloak               |        at org.keycloak.models.utils.KeycloakModelUtils.suspendJtaTransaction(KeycloakModelUtils.java:632)
keycloak               |        at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.waitForLock(LiquibaseDBLockProvider.java:95)
keycloak               |        at org.keycloak.services.resources.KeycloakApplication$1.run(KeycloakApplication.java:137)
keycloak               |        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:236)
keycloak               |        at org.keycloak.services.resources.KeycloakApplication.<init>(KeycloakApplication.java:130)
keycloak               |        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
keycloak               |        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
keycloak               |        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
keycloak               |        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
keycloak               |        at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:150)
keycloak               |        at org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2209)
keycloak               |        at org.jboss.resteasy.spi.ResteasyDeployment.createApplication(ResteasyDeployment.java:299)
keycloak               |        at org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:240)
keycloak               |        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:113)
keycloak               |        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:36)
keycloak               |        at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
keycloak               |        at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
keycloak               |        at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
keycloak               |        at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:231)
keycloak               |        at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:132)
keycloak               |        at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:526)
keycloak               |        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:101)
keycloak               |        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:82)
keycloak               |        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
keycloak               |        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
keycloak               |        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
keycloak               |        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
keycloak               |        at java.lang.Thread.run(Thread.java:745)
keycloak               |        at org.jboss.threads.JBossThread.run(JBossThread.java:320)
keycloak               | Caused by: org.h2.jdbc.JdbcSQLException: Feature not supported: "autoServerMode && (readOnly || fileLockMethod == NO || fileLockMethod == SERIALIZED || inMemory)" [50100-173]
keycloak               |        at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
keycloak               |        at org.h2.message.DbException.get(DbException.java:171)
keycloak               |        at org.h2.message.DbException.get(DbException.java:148)
keycloak               |        at org.h2.message.DbException.getUnsupportedException(DbException.java:206)
keycloak               |        at org.h2.engine.Database.open(Database.java:555)
keycloak               |        at org.h2.engine.Database.openDatabase(Database.java:226)
keycloak               |        at org.h2.engine.Database.<init>(Database.java:221)
keycloak               |        at org.h2.engine.Engine.openSession(Engine.java:56)
keycloak               |        at org.h2.engine.Engine.openSession(Engine.java:160)
keycloak               |        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139)
keycloak               |        at org.h2.engine.Engine.createSession(Engine.java:122)
keycloak               |        at org.h2.engine.Engine.createSession(Engine.java:28)
keycloak               |        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:313)
keycloak               |        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105)
keycloak               |        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
keycloak               |        at org.h2.Driver.connect(Driver.java:73)
keycloak               |        at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:319)
keycloak               |        ... 43 more
keycloak               |
keycloak               | 17:17:23,018 INFO  [org.jboss.as.server] (Thread-2) WFLYSRV0220: Server shutdown has been requested.
keycloak               | 17:17:23,027 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 54) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./auth: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./auth: java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.keycloak.services.resources.KeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
keycloak               |        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:85)
keycloak               |        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
keycloak               |        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
keycloak               |        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
keycloak               |        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
keycloak               |        at java.lang.Thread.run(Thread.java:745)
keycloak               |        at org.jboss.threads.JBossThread.run(JBossThread.java:320)
keycloak               | Caused by: java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.keycloak.services.resources.KeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
keycloak               |        at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:162)
keycloak               |        at org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2209)
keycloak               |        at org.jboss.resteasy.spi.ResteasyDeployment.createApplication(ResteasyDeployment.java:299)
keycloak               |        at org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:240)
keycloak               |        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:113)
keycloak               |        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:36)
keycloak               |        at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
keycloak               |        at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
keycloak               |        at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
keycloak               |        at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:231)
keycloak               |        at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:132)
keycloak               |        at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:526)
keycloak               |        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:101)
keycloak               |        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:82)
keycloak               |        ... 6 more
keycloak               | Caused by: java.lang.RuntimeException: Failed to connect to database
keycloak               |        at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.getConnection(DefaultJpaConnectionProviderFactory.java:373)
keycloak               |        at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.lazyInit(LiquibaseDBLockProvider.java:65)
keycloak               |        at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.lambda$waitForLock$0(LiquibaseDBLockProvider.java:97)
keycloak               |        at org.keycloak.models.utils.KeycloakModelUtils.suspendJtaTransaction(KeycloakModelUtils.java:632)
keycloak               |        at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.waitForLock(LiquibaseDBLockProvider.java:95)
keycloak               |        at org.keycloak.services.resources.KeycloakApplication$1.run(KeycloakApplication.java:137)
keycloak               |        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:236)
keycloak               |        at org.keycloak.services.resources.KeycloakApplication.<init>(KeycloakApplication.java:130)
keycloak               |        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
keycloak               |        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
keycloak               |        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
keycloak               |        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
keycloak               |        at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:150)
keycloak               |        ... 19 more
keycloak               | Caused by: java.sql.SQLException: javax.resource.ResourceException: IJ000453: Unable to get managed connection for java:jboss/datasources/KeycloakDS
keycloak               |        at org.jboss.jca.adapters.jdbc.WrapperDataSource.getConnection(WrapperDataSource.java:146)
keycloak               |        at org.jboss.as.connector.subsystems.datasources.WildFlyDataSource.getConnection(WildFlyDataSource.java:66)
keycloak               |        at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.getConnection(DefaultJpaConnectionProviderFactory.java:367)
keycloak               |        ... 31 more
keycloak               | Caused by: javax.resource.ResourceException: IJ000453: Unable to get managed connection for java:jboss/datasources/KeycloakDS
keycloak               |        at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.getManagedConnection(AbstractConnectionManager.java:656)
keycloak               |        at org.jboss.jca.core.connectionmanager.tx.TxConnectionManagerImpl.getManagedConnection(TxConnectionManagerImpl.java:429)
keycloak               |        at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.allocateConnection(AbstractConnectionManager.java:747)
keycloak               |        at org.jboss.jca.adapters.jdbc.WrapperDataSource.getConnection(WrapperDataSource.java:138)
keycloak               |        ... 33 more
keycloak               | Caused by: javax.resource.ResourceException: IJ031084: Unable to create connection
keycloak               |        at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:343)
keycloak               |        at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.getLocalManagedConnection(LocalManagedConnectionFactory.java:350)
keycloak               |        at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createManagedConnection(LocalManagedConnectionFactory.java:285)
keycloak               |        at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreConcurrentLinkedDequeManagedConnectionPool.createConnectionEventListener(SemaphoreConcurrentLinkedDequeManagedConnectionPool.java:1319)
keycloak               |        at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreConcurrentLinkedDequeManagedConnectionPool.getConnection(SemaphoreConcurrentLinkedDequeManagedConnectionPool.java:496)
keycloak               |        at org.jboss.jca.core.connectionmanager.pool.AbstractPool.getSimpleConnection(AbstractPool.java:626)
keycloak               |        at org.jboss.jca.core.connectionmanager.pool.AbstractPool.getConnection(AbstractPool.java:598)
keycloak               |        at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.getManagedConnection(AbstractConnectionManager.java:590)
keycloak               |        ... 36 more
keycloak               | Caused by: org.h2.jdbc.JdbcSQLException: Feature not supported: "autoServerMode && (readOnly || fileLockMethod == NO || fileLockMethod == SERIALIZED || inMemory)" [50100-173]
keycloak               |        at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
keycloak               |        at org.h2.message.DbException.get(DbException.java:171)
keycloak               |        at org.h2.message.DbException.get(DbException.java:148)
keycloak               |        at org.h2.message.DbException.getUnsupportedException(DbException.java:206)
keycloak               |        at org.h2.engine.Database.open(Database.java:555)
keycloak               |        at org.h2.engine.Database.openDatabase(Database.java:226)
keycloak               |        at org.h2.engine.Database.<init>(Database.java:221)
keycloak               |        at org.h2.engine.Engine.openSession(Engine.java:56)
keycloak               |        at org.h2.engine.Engine.openSession(Engine.java:160)
keycloak               |        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139)
keycloak               |        at org.h2.engine.Engine.createSession(Engine.java:122)
keycloak               |        at org.h2.engine.Engine.createSession(Engine.java:28)
keycloak               |        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:313)
keycloak               |        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105)
keycloak               |        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
keycloak               |        at org.h2.Driver.connect(Driver.java:73)
keycloak               |        at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:319)
keycloak               |        ... 43 more`

**Comment by smirnp** [comment]
I focused on this message 
` Caused by: org.h2.jdbc.JdbcSQLException: Feature not supported: "autoServerMode && (readOnly || fileLockMethod == NO || fileLockMethod == SERIALIZED || inMemory)" [50100-173]`
and did a rebuild of container locally (from sources) without AUTO_SERVER=TRUE in connection-url in java:jboss/datasources/KeycloakDS.

Now it started to give me a following error:
`10:09:38,315 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (ServerService Thread Pool -- 51) The database is read only; SQL statement:
keycloak               | delete from OFFLINE_CLIENT_SESSION where USER_SESSION_ID not in  (select persistent1_.USER_SESSION_ID from OFFLINE_USER_SESSION persistent1_) [90097-173]
keycloak               | 10:09:38,344 INFO  [org.jboss.as.server] (Thread-2) WFLYSRV0220: Server shutdown has been requested.
keycloak               | 10:09:38,343 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 51) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./auth: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./auth: java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.keycloak.services.resources.KeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
keycloak               |        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:85)
keycloak               |        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
keycloak               |        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
keycloak               |        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
keycloak               |        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
keycloak               |        at java.lang.Thread.run(Thread.java:745)
keycloak               |        at org.jboss.threads.JBossThread.run(JBossThread.java:320)
keycloak               | Caused by: java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.keycloak.services.resources.KeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
keycloak               |        at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:162)
keycloak               |        at org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2209)
keycloak               |        at org.jboss.resteasy.spi.ResteasyDeployment.createApplication(ResteasyDeployment.java:299)
keycloak               |        at org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:240)
keycloak               |        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:113)
keycloak               |        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:36)
keycloak               |        at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
keycloak               |        at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
keycloak               |        at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
keycloak               |        at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:231)
keycloak               |        at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:132)
keycloak               |        at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:526)
keycloak               |        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:101)
keycloak               |        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:82)
keycloak               |        ... 6 more
keycloak               | Caused by: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute statement
keycloak               |        at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1692)
keycloak               |        at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1602)
keycloak               |        at org.hibernate.jpa.spi.AbstractEntityManagerImpl.throwPersistenceException(AbstractEntityManagerImpl.java:1700)
keycloak               |        at org.hibernate.jpa.spi.AbstractQueryImpl.executeUpdate(AbstractQueryImpl.java:70)
keycloak               |        at org.keycloak.models.jpa.session.JpaUserSessionPersisterProvider.clearDetachedUserSessions(JpaUserSessionPersisterProvider.java:179)
keycloak               |        at org.keycloak.models.sessions.infinispan.initializer.OfflineUserSessionLoader.init(OfflineUserSessionLoader.java:45)
keycloak               |        at org.keycloak.models.sessions.infinispan.initializer.InfinispanUserSessionInitializer$1.run(InfinispanUserSessionInitializer.java:110)
keycloak               |        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:236)
keycloak               |        at org.keycloak.models.sessions.infinispan.initializer.InfinispanUserSessionInitializer.getOrCreateInitializerState(InfinispanUserSessionInitializer.java:107)
keycloak               |        at org.keycloak.models.sessions.infinispan.initializer.InfinispanUserSessionInitializer.startLoading(InfinispanUserSessionInitializer.java:165)
keycloak               |        at org.keycloak.models.sessions.infinispan.initializer.InfinispanUserSessionInitializer.loadPersistentSessions(InfinispanUserSessionInitializer.java:88)
keycloak               |        at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProviderFactory$2.run(InfinispanUserSessionProviderFactory.java:101)
keycloak               |        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:236)
keycloak               |        at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProviderFactory.loadPersistentSessions(InfinispanUserSessionProviderFactory.java:92)
keycloak               |        at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProviderFactory$1.onEvent(InfinispanUserSessionProviderFactory.java:76)
keycloak               |        at org.keycloak.services.DefaultKeycloakSessionFactory.publish(DefaultKeycloakSessionFactory.java:67)
keycloak               |        at org.keycloak.services.resources.KeycloakApplication.<init>(KeycloakApplication.java:163)
keycloak               |        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
keycloak               |        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
keycloak               |        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
keycloak               |        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
keycloak               |        at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:150)
keycloak               |        ... 19 more
keycloak               | Caused by: org.hibernate.exception.GenericJDBCException: could not execute statement
keycloak               |        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
keycloak               |        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109)
keycloak               |        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:95)
keycloak               |        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:207)
keycloak               |        at org.hibernate.hql.internal.ast.exec.BasicExecutor.doExecute(BasicExecutor.java:91)
keycloak               |        at org.hibernate.hql.internal.ast.exec.BasicExecutor.execute(BasicExecutor.java:60)
keycloak               |        at org.hibernate.hql.internal.ast.exec.DeleteExecutor.execute(DeleteExecutor.java:111)
keycloak               |        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.executeUpdate(QueryTranslatorImpl.java:429)
keycloak               |        at org.hibernate.engine.query.spi.HQLQueryPlan.performExecuteUpdate(HQLQueryPlan.java:374)
keycloak               |        at org.hibernate.internal.SessionImpl.executeUpdate(SessionImpl.java:1348)
keycloak               |        at org.hibernate.internal.QueryImpl.executeUpdate(QueryImpl.java:102)
keycloak               |        at org.hibernate.jpa.internal.QueryImpl.internalExecuteUpdate(QueryImpl.java:405)
keycloak               |        at org.hibernate.jpa.spi.AbstractQueryImpl.executeUpdate(AbstractQueryImpl.java:61)
keycloak               |        ... 37 more
keycloak               | Caused by: org.h2.jdbc.JdbcSQLException: The database is read only; SQL statement:
keycloak               | delete from OFFLINE_CLIENT_SESSION where USER_SESSION_ID not in  (select persistent1_.USER_SESSION_ID from OFFLINE_USER_SESSION persistent1_) [90097-173]
keycloak               |        at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
keycloak               |        at org.h2.message.DbException.get(DbException.java:171)
keycloak               |        at org.h2.message.DbException.get(DbException.java:148)
keycloak               |        at org.h2.message.DbException.get(DbException.java:137)
keycloak               |        at org.h2.engine.Database.checkWritingAllowed(Database.java:1743)
keycloak               |        at org.h2.table.Table.checkWritingAllowed(Table.java:1068)
keycloak               |        at org.h2.engine.User.hasRight(User.java:114)
keycloak               |        at org.h2.engine.User.checkRight(User.java:100)
keycloak               |        at org.h2.command.dml.Delete.update(Delete.java:57)
keycloak               |        at org.h2.command.CommandContainer.update(CommandContainer.java:79)
keycloak               |        at org.h2.command.Command.executeUpdate(Command.java:235)
keycloak               |        at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:154)
keycloak               |        at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:140)
keycloak               |        at org.jboss.jca.adapters.jdbc.WrappedPreparedStatement.executeUpdate(WrappedPreparedStatement.java:537)
keycloak               |        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:204)
keycloak               |        ... 46 more`

**Comment by smirnp** [comment]
Looks like H2 makes its db readonly after machine crashes (https://groups.google.com/forum/#!topic/h2-database/h_IMzCqhrOw)

**Comment by MichaelRoeder** [comment]
Can you please make sure that it is not the problem described in the FAQ? 
https://github.com/hobbit-project/platform/wiki/FAQ#keycloak-jdbc-error

**Comment by MichaelRoeder** [comment]
As a Fallback solution, you can simply replace your local keycloak DB with the DB stored in github (https://github.com/hobbit-project/platform/tree/master/config/keycloak). You just would have to recreate your users and assign roles to them.

**Comment by smirnp** [comment]
Yes, it is #140 again. After crash the folders somehow lost the specified permissions

**Comment by MichaelRoeder** [comment]
Thanks. I will add that hint to the FAQ :wink:

**Comment by smirnp** [comment]
> As a Fallback solution, you can simply replace your local keycloak DB with the DB stored in github (https://github.com/hobbit-project/platform/tree/master/config/keycloak). You just would have to recreate your users and assign roles to them.

I have cloned the whole repo locally, so I'm having this files and suppose h2 works with them. 

Do you offer to replace it with online-stored files?

**Comment by smirnp** [comment]
> Thanks. I will add that hint to the FAQ 
No need, it was my fault :) I have cloned a new repo from 152 branch and did not set up the permissions. May be it makes sense to add permission setting to makefile or inder keycloak section in docker-compose file

**Comment by MichaelRoeder** [comment]
Ok. It was taken into account for #161
