### ISSUE TITLE
Docker push response with unauthorized: authentication required

### ISSUE THREAD

**Issue by TortugaAttack** [hobbit-project/platform#16]
If using Docker push to upload docker to gitlab, it response with
`unauthorized: authentication required` after the layer were uploaded, thus it can not pushed..

This happens if the connection is too slow.

**Comment by MichaelRoeder** [comment]
According to the Docker authentication guidelines (https://docs.docker.com/registry/spec/auth/token/) the client gets a token with a short livetime. If the client needs too much time to upload the data, the token is not valid anymore.

We need to check whether the lifetime of this token can be increased.

**Comment by MichaelRoeder** [comment]
Solved by increasing the timeout of the security token in the Gitlab configuration.
