### ISSUE TITLE
No save and delete buttons when editing challenge

### ISSUE THREAD

**Issue by denkv** [hobbit-project/platform#166]
![screenshot-2017-11-17 13 41 50 00 00-nlb1scmxjc](https://user-images.githubusercontent.com/30291622/32950255-01eaa1b2-cba6-11e7-8bc3-622437749817.png)

**Comment by Ennosigaeon** [comment]
I have fixed this minor issue while working on #90. Solution available in [feature/newStatusPage](https://github.com/hobbit-project/platform/tree/feature/newStatusPage)

**Comment by Ennosigaeon** [comment]
Closing as #90 is merged.

**Comment by smirnp** [comment]
Is it already working in the online platform?

**Comment by MichaelRoeder** [comment]
No, sry. We will create a new version and deploy it as soon as #193 has been fixed.

**Comment by smirnp** [comment]
How I can modify it? Just executing sparql query?

**Comment by MichaelRoeder** [comment]
Yes, you can manipulate the data in the store using SPARQL but please be careful when changing the data in the store :wink:
