### ISSUE TITLE
Hardcoded paths in storage-init.sh

### ISSUE THREAD

**Issue by kiat** [hobbit-project/platform#17]
in Script 

platform/config/db/storage-init.sh

paths are hardcoded 

On my system is the Virtuoso installation directory not on 

/opt/virtuoso-opensource

This should not be hardcoded and should be read from some environment variables.

**Comment by MichaelRoeder** [comment]
Since we are using a Docker container for the Virtuoso and the script is executed inside the container, the paths are always the same and can be hardcoded.

Executing a local Virtuoso might be possible but is not supported by the platform.
