### ISSUE TITLE
Benchmarking result

### ISSUE THREAD

**Issue by weekmo** [hobbit-project/platform#172]
Sometimes when you run an experiment, the result doesn't appear in the result table.

**Comment by smirnp** [comment]
Duplicates #159

**Comment by weekmo** [comment]
Thanks

**Comment by weekmo** [comment]
Experiment ID: 1511965130348, starting time 29.11.2017, 15:19, http://dbpedia.org/sparql is used
Experiment ID: 1511965143515, starting time followed the previous one, http://local-dbpedia:8890/sparql is used

**Comment by weekmo** [comment]
This problem happen when one makes the system private (permission).
In addition, in this case (when a system has private permission) challenge organiser can't see the system.

**Comment by smirnp** [comment]
You should put your system to repository with Internal permissions (to be seen by the platform)

**Comment by weekmo** [comment]
Now even with public permission it doesn't appear.
Like this 1519299043623

**Comment by smirnp** [comment]
Now this is also actual for me: 1520529269933

I cannot compare several runs

**Comment by MichaelRoeder** [comment]
Thanks to @mjovanovik we figured out that our query is causing the problem because it hits a default maximum result size limitation. Using pagination withing our SPARQL client should fix the issue.

**Comment by smirnp** [comment]
Thank you for helping!
