### ISSUE TITLE
Question about rabbitmq host

### ISSUE THREAD

**Issue by smirnp** [hobbit-project/platform#173]
Dear all,
When I'm starting containers with addEvnironment(HOBBIT_HOST, "rabbit") for them, then containers fail to find such host, while it is configured (and working) for docker-host machine. It works only if I specify something like this 172.17.0.1 instead of rabbitmq, but sometimes rabbit container is deploying in other subnetwork (e.g. 172.21.0.1) and I should manually reconfigure hostname for other components.
Could you please instruct me, how the platform handles that problem (making containers to resolve/import host-machine's /etc/hosts file)?
Thank you

**Comment by MichaelRoeder** [comment]
We add all containers to a (virtual) Docker network (either `hobbit` or `hobbit-core`). Our RabbitMQ instance is connected to both networks and available using its DNS name `rabbit`. Docker does not make use of `etc/hosts` files but uses a DNS server for the virtual networks to derive the ips of containers.

So most probably your problem is that your container (that you may have started manually) is not connected to the network. You can either do that while creating the container using `--network hobbit` or after creation using `docker network connect`.

For more help, a more detailed description of your use case would be helpful :wink:

**Comment by smirnp** [comment]
My containers are dynamically connect to the hobbit and hobbit-core networks just after start. 
At looked at ContainerManagerImpl class in platform repo, but did not found any dns-specific options in containers configuration - just connection to the networks. Does docker allows to ping its containers only by their name?

**Comment by MichaelRoeder** [comment]
> Does docker allows to ping its containers only by their name?

No, you can also use their IP. But since the IPs are assigned dynamically, it is easier to use the container names (which act as host name).

> Probably the problem is because I use container names different from the expected hostnames?

I do not really get what you are doing :confused: If your RabbitMQ container has a different name than `rabbit`, it can not be found :wink:

**Comment by smirnp** [comment]
`I do not really get what you are doing 😕 If your RabbitMQ container has a different name than rabbit, it can not be found 😉`

In SDK I dynamically run all the containers required for experiment (RabbitMq, DummyEvalStorage) and containers to be tested (BenchmarkController, SystemAdapter, etc). And the tested containers cannot found "rabbit" host, while rabbit container started and attached to the hobbit and hobbit-core networks.

Should started rabbit container be pingable as rabbit if I remove it from /etc/hosts at my machine?

**Comment by smirnp** [comment]
Here is output of `docker instect <rabbitContainerID>`:

` {
        "Id": "457d3ff8e8b2a6cc144c2bc98ef57f919729d4639c06d3c881a7cca33e40c1ea",
        "Created": "2017-11-17T16:41:56.268664707Z",
        "Path": "docker-entrypoint.sh",
        "Args": [
            "rabbitmq-server"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 26781,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-12-01T13:34:01.959386868Z",
            "FinishedAt": "2017-11-22T15:31:50.601085922Z"
        },
        "Image": "sha256:79a008b25962e1a143e02b37187f855cb224e2203b94cc9f87e81fe275660c9d",
        "ResolvConfPath": "/var/lib/docker/containers/457d3ff8e8b2a6cc144c2bc98ef57f919729d4639c06d3c881a7cca33e40c1ea/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/457d3ff8e8b2a6cc144c2bc98ef57f919729d4639c06d3c881a7cca33e40c1ea/hostname",
        "HostsPath": "/var/lib/docker/containers/457d3ff8e8b2a6cc144c2bc98ef57f919729d4639c06d3c881a7cca33e40c1ea/hosts",
        "LogPath": "/var/lib/docker/containers/457d3ff8e8b2a6cc144c2bc98ef57f919729d4639c06d3c881a7cca33e40c1ea/457d3ff8e8b2a6cc144c2bc98ef57f919729d4639c06d3c881a7cca33e40c1ea-json.log",
        "Name": "/rabbit",
        "RestartCount": 0,
        "Driver": "aufs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "5672/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "5672"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": null,
            "Name": "aufs"
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "746c6c48407ca585a34e693a8bfa6f79c75adb0674e0d6064fbec8753f99de6a",
                "Source": "/var/lib/docker/volumes/746c6c48407ca585a34e693a8bfa6f79c75adb0674e0d6064fbec8753f99de6a/_data",
                "Destination": "/var/lib/rabbitmq",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "457d3ff8e8b2",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "25672/tcp": {},
                "4369/tcp": {},
                "5671/tcp": {},
                "5672/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/lib/rabbitmq/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "GOSU_VERSION=1.10",
                "RABBITMQ_LOGS=-",
                "RABBITMQ_SASL_LOGS=-",
                "RABBITMQ_GPG_KEY=0A9AF2115F4687BD29803A206B73A36E6026DFCA",
                "RABBITMQ_VERSION=3.6.14",
                "RABBITMQ_GITHUB_TAG=rabbitmq_v3_6_14",
                "RABBITMQ_DEBIAN_VERSION=3.6.14-1",
                "HOME=/var/lib/rabbitmq"
            ],
            "Cmd": [
                "rabbitmq-server"
            ],
            "ArgsEscaped": true,
            "Image": "rabbitmq",
            "Volumes": {
                "/var/lib/rabbitmq": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "ac4d6a6703e0022f65d38c94a9c0bdf0d5fb2c9a1405d8d55d435380eec2d365",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "25672/tcp": null,
                "4369/tcp": null,
                "5671/tcp": null,
                "5672/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "5672"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/ac4d6a6703e0",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "hobbit": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "457d3ff8e8b2"
                    ],
                    "NetworkID": "576361a4e342c7be98b97e90c4ee4d5e8107a8a31740346942a9c6ef36dc7304",
                    "EndpointID": "67fa810be050a16808970e204939e034bd04e0dbaf6b5e22f27b7dc32a478b85",
                    "Gateway": "172.21.0.1",
                    "IPAddress": "172.21.0.3",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:15:00:03",
                    "DriverOpts": null
                },
                "hobbit-common": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "457d3ff8e8b2"
                    ],
                    "NetworkID": "fbe0a8b6f1c3cab4f38593e1cd11c68cd945e19d0d5c23155523c69a01f6def3",
                    "EndpointID": "22d73edab9e48147ade5bbf1482752bbd4e3e3fd57bd87c27bdbd1bb9fdd3189",
                    "Gateway": "172.22.0.1",
                    "IPAddress": "172.22.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:16:00:02",
                    "DriverOpts": null
                }
            }
        }
    }`
