### ISSUE TITLE
"Not found" instead of "loading..."

### ISSUE THREAD

**Issue by denkv** [hobbit-project/platform#176]
On pages like "experiment details", when the data is not retrieved yet, interface displays "not found" message. Some kind of "loading" of loading animation should be displayed instead.

**Comment by MichaelRoeder** [comment]
Reduced priority since there are much more important open issues.

**Comment by Ennosigaeon** [comment]
I have added that functionality to "experiment details" and "benchmark configuration". For all other sites, such functionality should already  be implemented.

**Comment by Ennosigaeon** [comment]
Closing as Pull Request was successfully merged.

**Comment by denkv** [comment]
Experiment details page still displays "No experiment results found" when waiting for API's response.
