### ISSUE TITLE
Question: System_finished_signal

### ISSUE THREAD

**Issue by smirnp** [hobbit-project/platform#177]
I'm running dockerized components locally (via [Java SDK](https://github.com/hobbit-project/java-sdk/)) where my systemAdapter should notify BenchmarkController about it's finish. Now the only way to do that is to send Docker_Container_Terminated signal (with containerID listed in BC lists). I order to run  my containers without platform-controller introduced System_finished_signal for local debugs in SDK and created a listener to it in SDK's unitTests (it works).

My question is the following: may the System_finished_signal be introduced in hobbit-core or it has some security/logical issues? (E.g. probably user can send this signal before his system really finished and start to communicate with evaluation module (which starts after the system should be finished)?)

**Comment by MichaelRoeder** [comment]
In the documentation, we might have described the workflow using a `SYSTEM_FINISHED_SIGNAL` to keep the explanation simple. However, this signal is simply not existing (sorry, if this caused you some headaches :worried: ). The platform sends the information about terminated containers using the [`DOCKER_CONTAINER_TERMINATED`](https://github.com/hobbit-project/core/blob/master/src/main/java/org/hobbit/core/Commands.java#L95) message. The BC will get it and [check whether the terminated container is one of its own containers](https://github.com/hobbit-project/core/blob/master/src/main/java/org/hobbit/core/components/AbstractBenchmarkController.java#L578-L614).

So for your SDK, you should provide the BC with some system container ID (done by adding this ID to the `START_BENCHMARK_SIGNAL` that is processed [here](https://github.com/hobbit-project/core/blob/master/src/main/java/org/hobbit/core/components/AbstractBenchmarkController.java#L535)). Later, you can send the [`DOCKER_CONTAINER_TERMINATED`] message with an exit code attached (typically 0) to indicate the the system is terminated.

**Comment by smirnp** [comment]
Thank you for your responce
