### ISSUE TITLE
New KPI fo QA

### ISSUE THREAD

**Issue by weekmo** [hobbit-project/platform#178]
for the large scale task the time out should not throw an error but should allow the module to use the number of questions answered so far as the basis of a new KPI. The rationale is that, when the platform times out, it means the system wasn’t able to cope with the volume of the latest set of questions, and different systems will fail at different volumes.
This new KPI could be then combined with the F measure to produce a new kind of F measure as the winning score.

**Comment by MichaelRoeder** [comment]
This is not really related to the platform, right? Can we close it?

**Comment by weekmo** [comment]
It's realated, but we increased the duration of the timeout, so l think the new duration is enough for systems to finish. And if they don't, it's fair enough to consider them failed.
So I think we can close the issue.

**Comment by MichaelRoeder** [comment]
thanks
