### ISSUE TITLE
Redis DB does not store the experiment queue persistently

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#183]
### Problem

When restarting the platform, I want my running experiment and the experiments from the queue executed. This is even more important for experiments that are part of a challenge.

At the moment, it seems like Redis is not configured to store the data persistently.

**Comment by earthquakesan** [comment]
Can be solved via [configuration](https://redis.io/topics/persistence):
```
appendonly yes
```

**Comment by MichaelRoeder** [comment]
Can this be added to the `docker-compose` file or do we need a separate config file for redis?

**Comment by earthquakesan** [comment]
The current redis is configured to (defaults):
```
127.0.0.1:6379> CONFIG GET save
1) "save"
2) "3600 1 300 100 60 10000"
```
That means that the queue is dumped every 3600 secs (hour) if there is 1 change, every 300 secs (5 mins) if there are 100 changes and every 60 secs (1 min) if there are 10000 changes.

The file is written to /data/dump.rdb:
```
127.0.0.1:6379> CONFIG GET dbfilename
1) "dbfilename"
2) "dump.rdb"
127.0.0.1:6379> CONFIG GET dir
1) "dir"
2) "/data"
```

The /data folder is mounted on our internal deployment repo, but not in this repo. I will add the mount, that would solve the issue.

**Comment by earthquakesan** [comment]
check the pull request [here](https://github.com/hobbit-project/platform/pull/204)

**Comment by earthquakesan** [comment]
https://github.com/hobbit-project/platform/pull/205
