### ISSUE TITLE
Multiple TTL files in one project

### ISSUE THREAD

**Issue by smirnp** [hobbit-project/platform#186]
I have 3 types of systems within one project, but now I have to create 3 repositories. 
So I'm facing with repositories per account limit and have to delete some other projects, which is annoying.

Is it possible to place multiple ttl-files to single repository? Maybe I can put files in different folders within one repo?

**Comment by MichaelRoeder** [comment]
The `system.ttl` can contain more than one `hobbit:System` and `hobbit:SystemInstance`.

Until now, we had the restriction that a `benchmark.ttl` can only contain a single `hobbit:Benchmark`. However, in the next release this restriction should be gone as well.

**Comment by smirnp** [comment]
Thank you!
