### ISSUE TITLE
List of systems that can be registered for a challenge seem to contain all known systems

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#193]
## Problem
(Seems to be #133, again :disappointed:)

The visibility of systems does not work when it comes to registering a system for a challenge. The user can see all systems in the list. It does not matter whether the systems API fits to the API of the challenge tasks benchmark leading to a huge list of systems that is not manageable and could lead to the registration of incompatible systems.

The following example shows the registration page for a single challenge task:
![hobbit gui 15](https://user-images.githubusercontent.com/6122307/35113120-b44ae0f0-fc80-11e7-8a84-66e975afacf3.png)

## Cause
The problem seems to be caused by the way the client tries to get the list of systems and possible registrations. The following requests are sent by the GUI client for generating the page.
```
http://localhost:8080/rest/system-provider/systems
```
Retrieves the list of all systems that are visible to the user.
```
http://localhost:8080/rest/system-provider/challenge-all-registrations/http%3A%2F%2Fw3id.org%2Fhobbit%2Fchallenges%23cc48752a-c0bd-44bd-86c8-65b8a1738917
```
Retrieves the list of all registrations of the challenge (not only the registrations that should be visible to the user).
```
http://localhost:8080/rest/challenges/http%3A%2F%2Fw3id.org%2Fhobbit%2Fchallenges%23cc48752a-c0bd-44bd-86c8-65b8a1738917
```
Retrieves the challenge bean of the challenge.

The problem is that the client would need to filter the systems based on the information whether their API fits to the API of the benchmark of each challenge task. However, this is not possible since the `SystemBean`s do not contain the APIs of the systems.

## Solution
I would propose to get away from using the `system-provider/systems` URL and `system-provider/challenge-all-registrations` on this page and 
- [x] extend the `TaskRegistrationBean` to contain a boolean flag whether a system is registered or not. 
- [x] The gui-client could call the already existing `system-provider/challenge-registrations` 
- [x] which could be extended to return a list of `TaskRegistrationBean`s including all beans that can be registered and with the `registered` flag set to `true` if the system is currently registered.

Note that these changes may influence the registration overview of the challenge owner (depending on its implementation).

**Comment by Ennosigaeon** [comment]
That would make life easier on the UI side. So, if you want to implement that approach go ahead.

**Comment by MichaelRoeder** [comment]
For `/challenges/{id}/register` screen of a challenge, the client should use the following two URLs (`{id}` stands for the challenge URI):
* `/rest/challenges/{id}` to get the general data of the challenge (including the labels for the tasks, etc.)
* `/rest/system-provider/challenge-registrations{id}` for getting the systems the user could register

I updated the response of the latter REST URL to
```json
[{
  "type":"extendedTaskRegistrationBean",
  "challengeId":"http://w3id.org/hobbit/challenges#cc48752a-c0bd-44bd-86c8-65b8a1738917",
  "registered":true,
  "systemId":"http://w3id.org/system#amlLinking",
  "taskId":"http://w3id.org/hobbit/challenges#cc48752a-c0bd-44bd-86c8-65b8a1738917_task1",
  "system":{
    "description":"Agreement Maker Light, Linking Benchmark. ",
    "id":"http://w3id.org/system#amlLinking",
    "name":"AgreementMakerLight-Linking"
}},{
  "type":"extendedTaskRegistrationBean",
  "challengeId":"http://w3id.org/hobbit/challenges#cc48752a-c0bd-44bd-86c8-65b8a1738917",
  "registered":false,
  "systemId":"http://w3id.org/system#limesV2",
  "taskId":"http://w3id.org/hobbit/challenges#cc48752a-c0bd-44bd-86c8-65b8a1738917_task1",
  "system":{
    "description":"LIMES, the Link Discovery Framework for Metric Spaces, is a framework for discovering links between entities contained in Linked Data sources. ",
    "id":"http://w3id.org/system#limesV2","name":"LIMES"
}}]
```
The `registered` attribute shows whether the system is already registered or not. Note that I added the necessary information about the registered system (including the label) as `system` attribute. So no additional call to get information about the systems should be necessary.

@Ennosigaeon **Note** that with #136 the system beans in the list above can have an `errorMessage` attribute. Such systems have to be handled as discussed in #136 (i.e., they shouldn't be listed in the list of systems that could be registered but should cause a warning or something similar). 

I implemented the my part in the `hotfix/challengeRegistration-193` branch. Until now the branch of issue 136 has not been merged into this branch. However, it might be a good idea to do that when it comes to finally testing whether the handling of faulty systems is correct.

**Comment by MichaelRoeder** [comment]
@Ennosigaeon any progress regarding this issue? At the moment, it blocks a part of our next steps.

**Comment by Ennosigaeon** [comment]
I have implemented the specified behaviour, however the registrations are not stored. I call SystemProviderResources#updateChallengeTaskRegistrations with the following payload to register 1 system for a task:

```
[
  {
    "challengeId": "http://w3id.org/hobbit/challenges#455cf574-7ac5-4a4a-944c-13b45ec36b35",
    "taskId": "http://w3id.org/hobbit/challenges#455cf574-7ac5-4a4a-944c-13b45ec36b35_task1",
    "systemId": "http://w3id.org/bench#virtuoso72

"
  }
]
```

I have attached to corresponding [log](https://github.com/hobbit-project/platform/files/1681728/log.txt) entries and I am not able to find the system id in this log.
@MichaelRoeder Any idea what's going wrong?

**Comment by MichaelRoeder** [comment]
I have cleaned the code for the registration of systems. Can you please adapt the gui-client so that it
1. returns all system registrations (not only the registrations with `"registered":true`)
2. add the flag whether the systems are registered or not.

So, assuming that you have two systems `A` and `B` but you only registered `A`, the client should sent
```json
[
  {
    "challengeId": "http://w3id.org/hobbit/challenges#455cf574-7ac5-4a4a-944c-13b45ec36b35",
    "taskId": "http://w3id.org/hobbit/challenges#455cf574-7ac5-4a4a-944c-13b45ec36b35_task1",
    "systemId": "http://example.org/A",
    "registered":true
  },
  {
    "challengeId": "http://w3id.org/hobbit/challenges#455cf574-7ac5-4a4a-944c-13b45ec36b35",
    "taskId": "http://w3id.org/hobbit/challenges#455cf574-7ac5-4a4a-944c-13b45ec36b35_task1",
    "systemId": "http://example.org/B",
    "registered":false
  }
]
```

**Comment by Ennosigaeon** [comment]
Challenge registrations are now persisted.
