### ISSUE TITLE
X509 sertificate is not valid

### ISSUE THREAD

**Issue by smirnp** [hobbit-project/platform#194]
Trying to do auth or upload anything and got the following error: 
Error response from daemon: Get https://git.project-hobbit.eu:4567/v2/: x509: certificate has expired or is not yet valid

**Comment by MichaelRoeder** [comment]
Dear all,

the problem has been fixed. Apologize for any inconveniences.

Cheers,
Michael

**Comment by smirnp** [comment]
It works. Thank you!

**Comment by smirnp** [comment]
The problem occured again

**Comment by smirnp** [comment]
It works. Thanks!
