### ISSUE TITLE
GUI: parameter modifications are not saving for task

### ISSUE THREAD

**Issue by smirnp** [hobbit-project/platform#200]
I'm clicking the 'Save' button after editing values of benchmark parameters, but changes not saved. 
The changes of the text description of the task were saved normally.

**Comment by smirnp** [comment]
May be it is somehow relevant with #201

**Comment by MichaelRoeder** [comment]
Did you tried to check whether the values have been changed using the SPARQL endpoint of the platform?
Note that for seeing challenges, you have to use the https://db.project-hobbit.eu/sparql-auth endpoint.

**Comment by Ennosigaeon** [comment]
Could be a duplicate of #201. If you set the value of a parameter with a default value, save the task and open it again, the default parameter is displayed again. If this is the case, this issue can be closed as duplicate and a fix is already provided in #282.
