### ISSUE TITLE
Frontend security issue: handlebars

### ISSUE THREAD

**Issue by earthquakesan** [hobbit-project/platform#212]
The handlebars dependency defined in package-lock.json has a known moderate severity security vulnerability in version range < 4.0.0 and should be updated

**Comment by MichaelRoeder** [comment]
See also https://github.com/hobbit-project/platform/network/dependencies#35635765

**Comment by Ennosigaeon** [comment]
This is a known issue (see https://github.com/angular/angular-cli/issues/8534) and already fixed for angular-cli v1.5.3. As we are currently using angular-cli v1.2.6 I would suggest to simply update to current version v1.6.x.

**Comment by MichaelRoeder** [comment]
Sounds good to me. Please do so.

**Comment by Ennosigaeon** [comment]
I have updated all dependencies, especially Angular to version 5.2.3 and angular-cli to 1.6.7. Furthermore, I have made some minor UI improvements during testing.

**Comment by MichaelRoeder** [comment]
Fixed in develop.
