### ISSUE TITLE
riak fails to start within 15 seconds

### ISSUE THREAD

**Issue by vpapako** [hobbit-project/platform#231]
## Problem

basho-riak-kv fails to start before timeout of 15 seconds reached, so the experiment stacks in "waiting for all components to be initialized" state.

### Platform logs:

- `platform-controller_1  | 2018-03-07 14:14:01,013 INFO [com.spotify.docker.client.DefaultDockerClient] - <Creating container with ContainerConfig: ContainerConfig{hostname=basho-riak-k-e5cb4306b2bb41c781624cd24675fcc3, domainname=null, user=null, attachStdin=null, attachStdout=null, attachStderr=null, portSpecs=null, exposedPorts=null, tty=null, openStdin=null, stdinOnce=null, env=[HOBBIT_CONTAINER_NAME=basho-riak-k-e5cb4306b2bb41c781624cd24675fcc3, constraint:org.hobbit.workergroup==benchmark, CLUSTER_NAME=riakkv, HOST=0.0.0.0, HOBBIT_RABBIT_HOST=rabbit, HOBBIT_SESSION_ID=1520428194957], cmd=null, image=git.project-hobbit.eu:4567/gitadmin/basho-riak-kv:1.0.0, volumes={}, workingDir=null, entrypoint=null, networkDisabled=null, onBuild=null, labels={org.hobbit.parent=fbada19f79c36b536f41c8e9bd6b647da9f95bb2062c0e2e0da40e316e7c7994, org.hobbit.type=data}, macAddress=null, hostConfig=null, stopSignal=null, healthcheck=null, networkingConfig=null}>`

- `platform-controller_1  | 2018-03-07 14:14:33,536 INFO [org.hobbit.controller.PlatformController] - <Container 91d9d125d9e99f6b82d18faa6473bce947a23944370a4a92ac123f2f3a73f211 stopped with exitCode=1>`

- `platform-controller_1  | 2018-03-07 14:14:33,540 INFO [org.hobbit.controller.PlatformController] - <received command: session=BROADCAST, command=DOCKER_CONTAINER_TERMINATED>`

### Riak-kv logs:
`...`
`riak failed to start within 15 seconds,
see the output of 'riak console' for more information.
If you want to wait longer, set the environment variable
WAIT_FOR_ERLANG to the number of seconds to wait.`

### Possible solution
Increase the 15 seconds timeout to a higher value e.g. 60 sec.

**Comment by denkv** [comment]
This was fixed (timeout made configurable and increased) in our fork of the riak image.
