### ISSUE TITLE
Reading file from hobbitdata.informatik.uni-leipzig.de

### ISSUE THREAD

**Issue by mirkospasic** [hobbit-project/platform#234]
I've just noticed that reading file from ftp server stopped working. I have a lot of datasets uploaded there, but I cannot read it from my java code, any more:
IOUtils.toString(new URL("http://hobbitdata.informatik.uni-leipzig.de/mighty-storage-challenge/Task2/sf1/dataset_files.txt"))
This should return the content of the file, but it returns the string "Found" all the time. I guess that it is related to the http server itself. This code used to work a month ago.

PS: I know that this is not the platform issue, but the cluster configuration problem, but I hope that I can report it here.

**Comment by earthquakesan** [comment]
Hi @mirkospasic!

I've reproduced your issue from my PC:
```
~ % curl -v http://hobbitdata.informatik.uni-leipzig.de/mighty-storage-challenge/Task2/sf1/dataset_files.txt
*   Trying 139.18.121.22...
* TCP_NODELAY set
* Connected to hobbitdata.informatik.uni-leipzig.de (139.18.121.22) port 80 (#0)
> GET /mighty-storage-challenge/Task2/sf1/dataset_files.txt HTTP/1.1
> Host: hobbitdata.informatik.uni-leipzig.de
> User-Agent: curl/7.55.1
> Accept: */*
> 
< HTTP/1.1 302 Found
< Location: https://hobbitdata.informatik.uni-leipzig.de:443/mighty-storage-challenge/Task2/sf1/dataset_files.txt
< Date: Thu, 08 Mar 2018 13:40:08 GMT
< Content-Length: 5
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host hobbitdata.informatik.uni-leipzig.de left intact
Found
```

What you see is [HTTP response code 302](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302). It redirects you to https://... . What you can do to solve the problem:
1. Change http to https everywhere in your code
```
~ % curl https://hobbitdata.informatik.uni-leipzig.de/mighty-storage-challenge/Task2/sf1/dataset_files.txt  
social_network_activity_0_0.ttl.gz
social_network_person_0_0.ttl.gz
social_network_static_0_0.ttl.gz
```
2. Enable your code to follow redirection (in curl I can do it with -L flag)
```
~ % curl -L http://hobbitdata.informatik.uni-leipzig.de/mighty-storage-challenge/Task2/sf1/dataset_files.txt
social_network_activity_0_0.ttl.gz
social_network_person_0_0.ttl.gz
social_network_static_0_0.ttl.gz
```

**Comment by mirkospasic** [comment]
@earthquakesan 
Thank you!
