### ISSUE TITLE
Invalid Systems warning

### ISSUE THREAD

**Issue by smirnp** [hobbit-project/platform#253]
Hi! 
I see a warning about invalid systems - some participant uploaded system with the same url, as I used for my system. Now my system is not in the list and I cannot run it without modification of system.ttl. 
Can this functionality consider the upload/change time and not ban a system, which have been uploaded earlier?

**Comment by MichaelRoeder** [comment]
The feature should alread do exactly that. It uses the creation time of a project to determine which system is the original system (that should not be "banned").

Can you please provide the URI of the system and the git project URL?

**Comment by smirnp** [comment]
http://project-hobbit.eu/sml-benchmark-v2/system-adapter
