### ISSUE TITLE
Login to the RabbitMQ via GUI

### ISSUE THREAD

**Issue by HamidJalali** [hobbit-project/platform#263]
I installed the platform locally on my computer and i am now trying to login to the RabbitMQ via the GUI which is provided at the http://localhost:8081/ address. How can i login to the RabbitMQ what is the username and the password for it?

**Comment by MichaelRoeder** [comment]
If you are using the `rabbit:management` image as it is defined in the [docker-compose file](https://github.com/hobbit-project/platform/blob/master/docker-compose.yml#L53) you should have a RabbitMQ broker with a UI that you can access via `8081` (assuming that you have forwarded the port as done in the provided [docker-compose file](https://github.com/hobbit-project/platform/blob/master/docker-compose.yml#L58)).

Which OS are you using? For Linux distributions, forwarded ports are typically available via localhost. However, for other OS a VM is used to execute Docker and the IP of this VM has to be used.

**Comment by HamidJalali** [comment]
I am using Ubuntu 16.04 LTS as OS and i can access the RabbitMQ UI via 8081without any problem but i did not find informations about the login of the rabbitmq. 


![rabbitmq ui](https://user-images.githubusercontent.com/36888678/38804756-c5f47982-4173-11e8-93f2-d4bb6c18c902.png)

**Comment by MichaelRoeder** [comment]
It has the default settings, i.e., user `guest` with password `guest` (see https://www.rabbitmq.com/management.html)

**Comment by HamidJalali** [comment]
Thank you very much!
