### ISSUE TITLE
Retrieval of big logs

### ISSUE THREAD

**Issue by earthquakesan** [hobbit-project/platform#264]
Retrieval of the logs for the systems with a lot of log messages fails Elasticsearch. Sorting operation consumes all available memory.

Possible fix: disable sorting (increasing RAM).

**Comment by MichaelRoeder** [comment]
Would a LIMIT help? Most probably not, since Elasticsearch would have to apply the sorting before the limit, right? :thinking: 

Do you tried it without a sort? The messages still should have the correct order since that is the order in which they have been added to the index, right?

**Comment by earthquakesan** [comment]
The solution: if the resultset is more that 100k, don't do sorting.
