### ISSUE TITLE
Remove unnecessary image pulling to the local docker daemon

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#274]
## Description

From older versions the platform controller still has the ability to pull docker images to the local machine if the image is not available. However, in a swarm setup this does not make sense, anymore. The swarm is more independent and will pull the image by itself if it is not available.

## Solution
The usage of the [`pullImageIfNeeded`](https://github.com/hobbit-project/platform/blob/master/platform-controller/src/main/java/org/hobbit/controller/docker/ContainerManagerImpl.java#L223) method should be removed and the method should be marked as deprecated.

This will also solve #24

**Comment by denkv** [comment]
We can just [remove `pullImageIfNeeded`](https://github.com/hobbit-project/platform/pull/290) since it's unused and private.
