### ISSUE TITLE
Question about terminating components

### ISSUE THREAD

**Issue by smirnp** [hobbit-project/platform#275]
Hi!

Does a components (like task generator, systemAdapter) control the state of their incoming queues, when they receive a signal to terminate? 

E.g. a systemAdapter is much slower than the task generator and it receives a `TaskGenerationFinished` message, while its `taskGen2SystemAdapter` queue is still full of unprocessed tasks. Will it be terminated without finishing the queue?

It seems to me that I have seen handling of such a condition, but cannot find it anywhere in components code.

**Comment by MichaelRoeder** [comment]
Yes, a component should consume all the remaining messages. In your example, the signal only informs that there won't be new tasks generated. However, the already generated tasks should be consumed :wink: 

[`Our implementation`](https://github.com/hobbit-project/core/blob/master/src/main/java/org/hobbit/core/rabbit/DataReceiverImpl.java#L175) is pretty simple. If a signal should cause the termination, the `runFlag` in the following piece of code is set to `false`. However, messages can still be received and processed as long as the queue is not emtpy or the last attempt to get a message was successful.
```java
    Delivery delivery = null;
    while (runFlag || (queue.messageCount() > 0) || (delivery != null)) {
        delivery = consumer.nextDelivery(3000);
        // process delivery
    }
```
