### ISSUE TITLE
Lost tuples between multithreaded components

### ISSUE THREAD

**Issue by smirnp** [hobbit-project/platform#284]
Hi!
I'm experimenting with multi threaded components (taskGenerator, system, Storage with generator acknowledgement) based on standard DataSenderImpl/DataReceiverImpl and face with lost tuples between components. 
From senders tuples are looking sent without errors, but receivers usually receive N-1, N-2 tuples. 
With a single threaded components such a problem does not occur. 

Have you ever faced with this?

**Comment by MichaelRoeder** [comment]
Yes, we had such problems at the very beginning. However, we have implemented JUnit tests for scenarios like that and the problems have been fixed.

Do you have an implementation of this experiment, somewhere?
