### ISSUE TITLE
`Register system` button allows to register/unregistered other user's systems

### ISSUE THREAD

**Issue by smirnp** [hobbit-project/platform#288]
Hi!

It seems to me, that such a bug was already fixed, but participants continue reporting about it.

I see a number of systems, but definitely not all systems compatible with a benchmark. 

It's rather critical for those, who registered their systems....

**Comment by MichaelRoeder** [comment]
That is not really a bug. It is bound to the "visibility" of the systems. If the participants can see the system of other participants, these other systems are defined in projects with the visibility "protected" or "public".

As long as nobody unregisters a system which is not known owned by him, everything should be fine.
