### ISSUE TITLE
Auth Error when starting Platform on localhost

### ISSUE THREAD

**Issue by TortugaAttack** [hobbit-project/platform#29]
If the Platform and Keycloak is started on localhost or 127.0.0.1. 
Keycloak will throw an 401 Error. 
Further on if one tries to access the Platform GUI with either 127.0.0.1 or 0.0.0.0 instead of the local IP (e.g. 192.162.1.3) it does nothing else but showing "Loading..." 
If one access with the local IP the GUI will load but you can not start a Benchmark, as the previous mentioned 401 Error occurs.

**Comment by TortugaAttack** [comment]
A current workaround is: 
Find your local IP with `ifconfig`
in the `docker-compose.yml` change the the `KEYCLOAK_AUTH_URL` parameter to `http://your-local-ip:8181/auth` and start everything. 
Access Keycloak using `your-local-ip:8181` add the IP to the valid Redirects and web origins as mentioned in the Readme. 
Access the GUI with `your-local-ip:8080`and everything should work

**Comment by MichaelRoeder** [comment]
This issue was reported for deploying the platform locally on a Linux distribution.

**Comment by yamalight** [comment]
@MichaelRoeder this looks like the same issue that was solved by this: https://github.com/hobbit-project/platform/issues/18#issuecomment-298050869

**Comment by MichaelRoeder** [comment]
Yes, you are right. Marking it as duplicate.

It will be solved as soon as the solution of #18 is implemented.

**Comment by MichaelRoeder** [comment]
Solution for this is decribed at https://github.com/hobbit-project/platform/issues/18#issuecomment-318602899
