### ISSUE TITLE
Experiment can stop platform components communication

### ISSUE THREAD

**Issue by Kleanthi** [hobbit-project/platform#304]
## Original message
The platform GUI is not working. It seems to be loading the pages, but I can only see the headers.

## Problem description

The problem is caused by an experiment that is generating a large number of messages while the receiver is not consuming them. The RabbitMQ broker reacts correctly by stopping to accept messages.
```
**********************************************************
*** Publishers will be blocked until this alarm clears ***
**********************************************************

=INFO REPORT==== 15-May-2018::13:04:53 ===
vm_memory_high_watermark clear. Memory used:1713598464 allowed:1717986918

=WARNING REPORT==== 15-May-2018::13:04:53 ===
memory resource limit alarm cleared on node rabbit@093e1f328ab0

=WARNING REPORT==== 15-May-2018::13:04:53 ===
memory resource limit alarm cleared across the cluster

=INFO REPORT==== 15-May-2018::13:05:13 ===
vm_memory_high_watermark set. Memory used:1718415360 allowed:1717986918

=WARNING REPORT==== 15-May-2018::13:05:13 ===
memory resource limit alarm set on node rabbit@093e1f328ab0.
```
However it is doing that for all messages - including the messages that are necessary for the communication between the platform components

## Solution
1. It might be possible to separate the experiment queues from the platform queues inside the broker to make sure that the platform queues have their own amount of memory
2. A fallback solution would be to introduce a second broker that to have one broker for the platform and a second broker for the experiment.

**Comment by MichaelRoeder** [comment]
I can not reproduce the problem :confused: 
Can you please check it again?

**Comment by Kleanthi** [comment]
The problem occurred yesterday for 3-4 hours. Now everything is back to normal.

**Comment by MichaelRoeder** [comment]
The problem is caused by RabbitMQ which stops forwarding messages.
```
**********************************************************
*** Publishers will be blocked until this alarm clears ***
**********************************************************

=INFO REPORT==== 15-May-2018::13:04:53 ===
vm_memory_high_watermark clear. Memory used:1713598464 allowed:1717986918

=WARNING REPORT==== 15-May-2018::13:04:53 ===
memory resource limit alarm cleared on node rabbit@093e1f328ab0

=WARNING REPORT==== 15-May-2018::13:04:53 ===
memory resource limit alarm cleared across the cluster

=INFO REPORT==== 15-May-2018::13:05:13 ===
vm_memory_high_watermark set. Memory used:1718415360 allowed:1717986918

=WARNING REPORT==== 15-May-2018::13:05:13 ===
memory resource limit alarm set on node rabbit@093e1f328ab0.
```

**Comment by MichaelRoeder** [comment]
Updated issue description.

**Comment by MichaelRoeder** [comment]
Decision: add a second message broker to separate the communication of the platform from the communication of experiment components.
