### ISSUE TITLE
Repeatable challenge seems to delete registrations of other challenges

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#308]
## Problem

Challenge A (http://w3id.org/hobbit/challenges#33578642-2a74-4a95-8f9b-24a6f675937f) is a repeatable challenge and has two tasks similar to Challenge B (http://w3id.org/hobbit/challenges#b01114df-13e5-45c0-956d-9c6ee26c1625). 9 Systems where registered for all 4 tasks. However, after the platform executed the next round of tasks for A, the 9 registrations for the second task of challenge B have been deleted.

**Comment by smirnp** [comment]
For now I see the following (haven't changed anything since yesterday):
Challenge A has 9 registered systems for task_2 (while it is hidden from registrations)
Challenge B has 0 registered systems at all (yesterday it was 9)

**Comment by MichaelRoeder** [comment]
Did you have edited one of the tasks?
I just saw that editing a task removes all registrations from that task :disappointed:

**Comment by smirnp** [comment]
For challenge B - not changed anything.
For challenge A I see 18 registered systems in GUI, but in sparql I don't see any involvesSystemInstance triple: https://db.project-hobbit.eu/sparql-auth?default-graph-uri=&query=select+distinct+%3Fg+%3Fp+%3Fo+where+%7B+graph+%3Fg+%7B%3Chttp%3A%2F%2Fw3id.org%2Fhobbit%2Fchallenges%2333578642-2a74-4a95-8f9b-24a6f675937f%3E+%3Fp+%3Fo.%7D%7D+LIMIT+100&format=text%2Fhtml&timeout=0&debug=on

**Comment by MichaelRoeder** [comment]
The registrations are added to the tasks. So you will find the registrations of task 1 if you ask for the triples of task 1 (task 1 URI = challenge URI + "_task1").

**Comment by smirnp** [comment]
Yes, you are right:) My mistake
