### ISSUE TITLE
Experiment result is trimmed

### ISSUE THREAD

**Issue by romromov** [hobbit-project/platform#31]
S2R:
1. Run some experiment where kpi has a long value.

Result:
1. Only part of the value is visible

Expected:
1. The value should fully visible since it conveys important information

![image](https://cloud.githubusercontent.com/assets/18396026/24979812/ee4552dc-1fd5-11e7-9d6a-6c44abbf4555.png)

**Comment by MichaelRoeder** [comment]
@romankorf Is there an easy way to insert line breaks into the results?

**Comment by MichaelRoeder** [comment]
Solved in `v1.0.6`.

Note that it might be needed to reload the page with `Shift` + `F5` to make sure that the cache is deleted.
