### ISSUE TITLE
Experiments column in "Experiments results" is trimmed

### ISSUE THREAD

**Issue by romromov** [hobbit-project/platform#32]
![image](https://cloud.githubusercontent.com/assets/18396026/25070704/5fbc915a-22a6-11e7-8c0d-a9da6d5e7dc0.png)

**Comment by MichaelRoeder** [comment]
Do you mean that the name of the challenge in the fourth column is trimmed?

**Comment by romankorf** [comment]
Issue solved with the fix of issue #75

**Comment by Ennosigaeon** [comment]
This issue becomes obsolete with merging #104.
