### ISSUE TITLE
Can insert string into integer field

### ISSUE THREAD

**Issue by earthquakesan** [hobbit-project/platform#322]
When editing task for a challenge I can put any arbitrary string into any field of the task. Most of the fields for tasks are integers. After putting string into a field, saving and editing a task again, the field will be empty.

There should be a check for an input value on both client and server side (ie GUI frontend and backend).

**Comment by MichaelRoeder** [comment]
This functionality was in the old UI. It was also the reason why we introduced the list of datatypes - to make the UI aware of the expected type.

**Comment by Ennosigaeon** [comment]
The UI is able to correctly set the input types (see for example _Data Storage Benchmark v2.0_). Types are selected based on the `datatype` field. `xsd:integer`, `xsd:unsignedInt`, `xsd:decimal`, `xsd:float` and `xsd:double` are interpreted as numbers, all other input types as a text input. 

Please reopen this ticket, if you have a specific example where the input type is inferred incorrectly.
