### ISSUE TITLE
Introduce user friendly logs

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#323]
## Description

As a user, I would like to have a format that is easier to read than the currently returned JSON. Several solutions are possible:
* Visualize the log in the GUI.
* transform the log in the server backend into a CSV, TSV or simple TXT file.

## CSV Example

It should be easy to transform the JSON objects
```json
[{"_index":"logstash-2018.05.02","_type":"other","_source":{"image_name":"git.project-hobbit.eu:4567/gitadmin/platform-benchmark-system:latest","@timestamp":"2018-05-02T09:59:03.960Z","container_name":"platform-benchmark-system-790c8eeae9e94c46bcfad626f1b77a84.1.pj0qm9q0z9qsklbxjtnz6j3ri","message":"PlatformBenchmarkingSystem started","container_id":"921f980a5fbec59140fff75cd9443832345d2cfc88cfc98317f8d0f8e93c9c68"},"_id":"AWMgSoIeyj7vYW0cgVcA","sort":[1525255143960],"_score":null}]
```
into a CSV file like
```csv
"@timestamp","image_name","container_id","message"
"2018-05-02T09:59:03.960Z","git.project-hobbit.eu:4567/gitadmin/platform-benchmark-system:latest","921f980a5fbec59140fff75cd9443832345d2cfc88cfc98317f8d0f8e93c9c68","PlatformBenchmarkingSystem started"
```

**Comment by MichaelRoeder** [comment]
Implemented necessary changes in the backend in feature/userFriendlyLogs-323.

The backend offers the submission of a `format` parameter which can have one of the following values: `JSON`, `CSV` or `TXT`. The front end should offer additional buttons (one for each format).

**Comment by Ennosigaeon** [comment]
Changes in GUI are now available in feature/userFriendlyLogs-323. Please note, that their will probably a merge conflict with #342.
