### ISSUE TITLE
Can not open the link for the description of the Data Generator

### ISSUE THREAD

**Issue by HamidJalali** [hobbit-project/platform#326]
Good evening,

i just wanted to read the description of the Data Generator but was not able to access the tutorial. The reason why i cant access the link is described as: "You dont have permission to update this wiki".

The screenshots are depicted below: 

![github_data_generator](https://user-images.githubusercontent.com/36888678/40880103-291666c2-66ab-11e8-91b9-906b6743c33a.png)

![error_message_github](https://user-images.githubusercontent.com/36888678/40880107-3790f82a-66ab-11e8-86ec-841fb842c140.png)

Thank you in advance.

**Comment by MichaelRoeder** [comment]
Thanks for this important hint. I updated the page and removed these old links.

The [overview page](https://github.com/hobbit-project/platform/wiki/Overview) should already explain the role of the different components.
