### ISSUE TITLE
Issues with instructions of deploying the platform locally

### ISSUE THREAD

**Issue by Kleanthi** [hobbit-project/platform#330]
Here are some issues I found when I tried to follow the [instructions](https://github.com/hobbit-project/platform)  to install the platform locally. **Please note that my intention was to execute an experiment using an existing benchmark and an existing system using my laptop with the following hardware specs:**
`Architecture:          x86_64`
`CPU op-mode(s):        32-bit, 64-bit`
`Byte Order:            Little Endian`
`CPU(s):                4`
`Model name:            Intel(R) Core(TM) i5-3340M CPU @ 2.70GHz`
`CPU MHz:               1698.785`
`CPU max MHz:           3400.0000`
`CPU min MHz:           1200.0000`

1. `docker-compose up virtuoso    `                                                                                        (master✱) 
`ERROR: No such service: virtuoso`
It should be `docker-compose up vos`

2. Once the user runs docker-compose up vos, add that you have to open a new terminal (without closing the current one) and from the platform folder the user should run ./run-storage-init.sh 

3. I got the following issue when executing run-storage-init.sh 
`./run-storage-init.sh `                                                                                                (master✱) 
`192bafd7133d 8820f9e44667
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"8820f9e44667\": executable file not found in $PATH": unknown`

It was caused because I had another vos container. I think the script should check if more than one vos container is present.

4. It is not mentioned somewhere if the user can close the terminals he/she used to run Virtuoso and Keycloack. While running the platform locally, shutting down Keycloack will not allow the user to use the platform GUI. Shutting down Virtuoso, the Experiment Results tab shows no experiments. So please mention that the user can shut them down before running the platform, not during.

5. The command `docker inspect --format='{{.NetworkSettings.Networks.hobbit.IPAddress}}' platform2_keycloak_1` does not work. Instead `KEYCLOAK_AUTH_URL=http://localhost:8181/auth` should work just fine.

6. The command `iptables -A INPUT -i br-5c9d73b080ad -j ACCEPT` works only if you are root. So it should be `sudo iptables -A INPUT -i br-5c9d73b080ad -j ACCEPT`.

7. There is not tab `Role Mappings` in the Keycloack page. 

8. The whole `Details of the user management` section in the instructions does not mention whether or not this is obligatory to do. Also there is no description why the user should follow these instructions. It is a very confusing section and must be revised. 

9. `Login to the Hobbit git`, please provide a link for this. Also explain how can someone ask for an account there or give a link to follow instructions. Also you click on your Profile picture, then on Settings. Then on the menu bar on the right you click on the `Access Tokens`. 

10. Please include that you must uncomment the following lines:
      `  GITLAB_USER=user`
      ` GITLAB_EMAIL=user@provider.org`
      ` GITLAB_TOKEN=ABC-XYZ`

11. Once the token is created, it will not be displayed again, so mention with bold capital letters that the user has to copy paste it straight away. Also, if the user has lost it, mention that they must create a new one.

12. Please provide an instruction on how to completely shut down the platform once the user is done.

13. Also the runtime of an experiment locally is not the same as the one in the platform. Please provide a way to fix this. There is a [page](https://github.com/hobbit-project/platform/wiki/Configuration-parameters) with description of the parameters, but no link about it in the instructions file.

14. There are no instructions on how to identify any experiment errors by checking logs. It should not be assumed that the user is super familiar with docker and has knowledge of commands such as `docker ps -a`, `docker logs <container_id> ` etc. A detailed set of instructions might not be possible, but a basic guideline is recommended.  Also it is highly recommended that users deletes all stopped containers using the command  `docker rm $(docker ps -a -q)` after an experiment is executed. At some point the list of containers grows large when executing multiple experiments and makes the debugging a bit more difficult. 

15. Mention somewhere that the ability to run an experiment with e.g. large datasets, depends on the user's hardware and not on the platform itself.

16. I tried to execute a small experiment using the platform locally. It terminated with the following error 
`<Got exception while trying to request the creation of an instance of the "git.project-hobbit.eu:4567/defaulthobbituser/defaultevaluationstorage:1.0.7-SNAPSHOT" image.>`
Once I executed the same experiment again, there was no problem. I did not restart the platform.

While I was trying to run the platform locally, I was in contact with @MichaelRoeder who helped me overcome the above issues. Once I was done fixing these issues I was able to run an experiment successfully. I believe that all these errors should be fixed asap so the platform can be deployed locally.

**Comment by vpapako** [comment]
In the same context some more comments :

17. Elasticsearch runs as user `elasticsearch` using uid:gid 1000:1000. So, when mounting a host dir or a file, such as `config/elk/logs` or `config/elk/elasticsearch.yml` we need to ensure that is accessible by this user. For the data and log dirs, such as `config/elk/logs`, write access is required as well:
```
sudo chmod -R g+rwx config/elk
sudo chgrp -R 1000 config/elk/logs
```

18. New files created after Keycloak starts such as `keycloak.lock.db` or `keycloak.trace.db` are also created by user 1000:1000, so if there is not such a user, Keycloak cannot be started.

19. In the platform-controller/Makefile I had to connect the cAdvisor, and prometheus containers to the hobbit-core network (add `--network=hobbit-core`) in order for the cAdvisor metrics and prometheus container to be reachable by the platform controller.

**Comment by MichaelRoeder** [comment]
Regarding 18: In the [README file](https://github.com/hobbit-project/platform#configure-keycloak), there is alraedy the description that you need to allow other users to write to the keycloak directory. Wouldn't that be sufficient? Or am I misunderstanding the issue?

**Comment by vpapako** [comment]
Actually I was referring to the locally existence of a user with UID 1000. 

When I first tried to install the platform, there was not a user in my environment with an id 1000 and keycloak could not be started. I remember that such an issue fixed after assigning id 1000 to an existing user. But it was probably not what solved the problem, since I rechecked it by changing such user's id from 1000 to 4000 (so there is no user with id 1000) and keycloak seems not to be in trouble... :confused: 
So, I mark it as solved.

**Comment by vpapako** [comment]
20. By default, the logs of the containers of the platform are not accessible via kibana. Something like the following it would be good to be mentioned:

In order to let the logs of any platform container to be accessible via kibana, logging configuration have to be added in the appropriate service in `docker-compose-dev.yml` file:
```
logging:
  driver: gelf
  options:
    gelf-address: "udp://0.0.0.0:12201"
```

**Comment by MichaelRoeder** [comment]
Should be fixed at https://hobbit-project.github.io/quick_guide.html
