### ISSUE TITLE
Benchmark configuration is reset if a different system is chosen

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#340]
## Description

When a user chooses a benchmark On the configuration screen and changes the parameters, the configuration is set back to its default values when the user chooses the system. This should not happen since it forces the user to follow a certain order (1. choose the benchmark, 2. choose the system, 3. configure parameters) without expressing it explicitly.

## Solution

The parameters shouldn't be set to their default parameters just because a user chooses a new or different system.

**Comment by Ennosigaeon** [comment]
Fix is available in pull request #342
