### ISSUE TITLE
Pending and cancelled commits in gitlab

### ISSUE THREAD

**Issue by smirnp** [hobbit-project/platform#356]
Hi!

I have added a new file (benchmark.ttl), the benchmark appeared in the list, but commits are in pending status and finally they become cancelled

**Comment by smirnp** [comment]
https://git.project-hobbit.eu/sdk-examples/benchmark-controller/commits/

**Comment by MichaelRoeder** [comment]
The new Gitlab version came with an auto configured CI pipeline as default. This led to the commits to be "pending" until the CI pipeline generated a result (which was not working).

I turned it off for all projects. Please try it again.

**Comment by smirnp** [comment]
Now it works!
