### ISSUE TITLE
Add a license data

### ISSUE THREAD

**Issue by denkv** [hobbit-project/platform#435]
- add data with: license URL, license label, license image
- if there is license data, display it in the footer
- "[image] Data is licensed under ... and attributed to ..."

**Comment by MichaelRoeder** [comment]
I would suggest to add the following RDF triples to the public graph:
```turtle
@prefix xhv: <http://www.w3.org/1999/xhtml/vocab#> .
@prefix cc: <https://creativecommons.org/ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

<http://hobbit.org/graphs/PublicResults> a dcat:Dataset;
	cc:license <https://creativecommons.org/licenses/by/4.0/>;
	cc:attributionName "HOBBIT Project";
	cc:attributionURL <http://hobbit-project.eu> .

<https://creativecommons.org/licenses/by/4.0/> a cc:License;
	rdfs:label "CC BY 4.0";
	xhv:icon <https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/by.svg> .
```
The UI could check for this information and if it is available, show it in the front end.

**Comment by MichaelRoeder** [comment]
Please add a description how the license of the data can be defined to the documentation after its has been implemented.

**Comment by denkv** [comment]
When licensing information is not included in dataset, we can instead display something like "Data license is not specified in this dataset. How to do it?" with the link to relevant documentation.
