### ISSUE TITLE
UI shows results of challenges before publication date is reached

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#44]
## Problem

When executing a challenge, the results are visible for every user while they should be only visible to a) the owner of the challenge or b) the owner of the benchmarked system.

![expvisible](https://cloud.githubusercontent.com/assets/6122307/25695839/f7855af0-30b4-11e7-8648-1ef71d157afb.png)

Additionally, it can be seen that the challenge task column is empty although the first 4 experiments belong to a challenge.

However, the results of the experiments ,e.g., http://w3id.org/hobbit/experiments#1493885271690, are stored in the correct graph. Executing the SPARQL query
```
SELECT DISTINCT ?g ?p ?o WHERE { GRAPH ?g {<http://w3id.org/hobbit/experiments#1493885271690> ?p ?o}} LIMIT 100
```
creates the result

| g | p | o |
|---|---|---|
|http://hobbit.org/graphs/PrivateResults |http://www.w3.org/1999/02/22-rdf-syntax-ns#type |http://w3id.org/hobbit/vocab#Experiment |
|http://hobbit.org/graphs/PrivateResults |http://w3id.org/hobbit/vocab#involvesBenchmark |http://project-hobbit.eu/resources/debs2017/debsbenchmark |
http://hobbit.org/graphs/PrivateResults |http://w3id.org/hobbit/vocab#involvesSystemInstance |http://project-hobbit.eu/resources/debs2017/debsparrotsystemexample |
|... |... |... |

**Comment by MichaelRoeder** [comment]
## Recration of problem
1. Create a local `gitadmin` account
2. Create a challenge
    * Set the execution date to the current day
    * Set the publication date to a day in the future
    * Mark the challenge as visible
    * Store the challenge
3. Create a challenge task
    * Choose the platform benchmark
    * choose a low number of queries, e.g., 1
    * Store the task
4. Register a system
    * Choose the platform system
5. Close the challenge
6. Logout and login with a different user (that does not have the challenge organizer role)

The challenge will be executed directly. After the experiment of the challenge has been executed, it won't be published since the publication date has not been reached. However, for the other user who a) is not the owner of the challenge (and has not even the challenge organizer role) and b) is not the owner of the system, the experiment is still listed in the list of all experiments.

**Comment by yamalight** [comment]
Looks like it's simply not implemented: https://github.com/hobbit-project/platform/blob/master/hobbit-gui/gui-serverbackend/src/main/java/de/usu/research/hobbit/gui/rest/ExperimentsResources.java#L91
