### ISSUE TITLE
Allow benchmarks to provide custom experiment status messages

### ISSUE THREAD

**Issue by denkv** [hobbit-project/platform#473]
Currently we have generic HOBBIT-provided messages like "Benchmark and system are initializing". We can allow benchmarks to provide custom status messages.

### Solutions
* benchmark sends a predefined command to the command queue, which includes status message and maybe other details
* we display the most recent log line which adheres to some agreed rule (maybe with a text like "Status: ..." or using other attributes of the log event)

**Comment by MichaelRoeder** [comment]
Duplicate of #119. Please update the already existing issue and close this one.
