### ISSUE TITLE
NaN values can not be handled by the storage

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#48]
## Problem

The open source virtuoso version hosted on docker hub can not handle `"NaN"^^xsd:double` triples.

```
Virtuoso S0022 Error SQ200: No column NaND.

SPARQL query:
define sql:big-data-const 0 
#output-format:text/html
define sql:signal-void-variables 1 PREFIX  bench: <http://w3id.org/bench#> 
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
INSERT DATA {   
    GRAPH <http://hobbit.org/graphs/PublicResults> {
        bench:Precision_Observation23_for_1494323941934 bench:precision "NaN"^^xsd:double .
    }
}
```

## Solution
Mirko pointed out, that the issue of handling "NaN" values should be fixed in newer versions of the open source Virtuoso (see https://github.com/openlink/virtuoso-opensource/issues/354 )

1. Check whether the problem is solved in the latest version
2. Compile the latest version, create a newer Docker image and uploading it to docker hub so that it can be used for the platform

**Comment by mjovanovik** [comment]
I explored this problem further and did some testing, and unfortunately, the issue still exists in all latest VOS versions:

- [Latest `stable/7` branch, VOS version 07.20.3217](https://github.com/openlink/virtuoso-opensource/tree/stable/7)
- [Latest `develop/7` branch, VOS version 07.20.3217](https://github.com/openlink/virtuoso-opensource/tree/develop/7)

The issue linked above refers to a different problem with "NaN" values, which seems to be solved.
