### ISSUE TITLE
Unset parameters cause HTTP 500

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#50]
## Problem
If 
* a benchmark does not define a default value for a parameter (e.g., ODIN) and
* a user starts an experiment choosing this benchmark without putting a value inside the field of this parameter

a `java.lang.NullPointerException` is thrown in the GUI serverbackend:
```
at de.usu.research.hobbit.gui.rabbitmq.PlatformControllerClient.addParameters(PlatformControllerClient.java:284)
```
because there is no Literal for the given parameter. The request of the GUI client is answered with HTTP 500.

The problem can even be reproduced by taking a benchmark and removing the default value of a parameter without setting a new value.

## Proposed solution
It should not be possible to submit an experiment if one of the parameters is empty.

**Comment by MichaelRoeder** [comment]
Added a more expressive error message. Unfortunately, the Front End still shows
`Response with status: 500 Request failed. for URL: http://192.168.99.100:8080/rest/benchmarks`. Maybe, a good way to bring an error message from the backend to the front end (i.e., to be visible for the user) would be good as well.

**Comment by romankorf** [comment]
Simple bugfix on https://github.com/hobbit-project/platform/tree/bug%2350
