### ISSUE TITLE
Experiment vanishes without a trace

### ISSUE THREAD

**Issue by MartinSchmitz95** [hobbit-project/platform#521]
Hello. I am implementing a Benchmark and a System for Hobbit. It works fine locally, but when I try to start the experiment on the platform the experiment vanishes without leaving any trace.

I am able to start the experiment over the UI and can select the benchmark and system properly.
Then my experiment gets queued. I can also check the experiment status while the experiment is in the queue.
However, when the experiment is supposed to start, it disappears. There is no error log or anything that would help me debugging.

Does anyone have a clue what is happening or  how I can find out where the problem is?

**Comment by denkv** [comment]
Is it "Martin Benchmark2"? In your `system.ttl` there's a missing `;` at line 8, so that system is not available for experiments. If that would be fixed, we can check the described issue.

**Comment by MartinSchmitz95** [comment]
Hello denkv, thank you for answering!
Yes exactly, its Martin Benchmark2.
I removed the `;`  to see if the behaviour changes when the metadata file is wrong formatted. I changed it back now and hope you can replicate my problem now.

**Comment by denkv** [comment]
Your benchmark resource in `benchmark.ttl` needs to have the main Docker image of your benchmark specified as `hobbit:imageName` property.

For example, `hobbit:imageName "git.project-hobbit.eu:4567/schmitz.kessenich/martin_benchmark/benchmark-controller"`.

**Comment by MartinSchmitz95** [comment]
It works, thank you so much!!!
