### ISSUE TITLE
Remove empty KPIs from the Experiment Details page

### ISSUE THREAD

**Issue by mjovanovik** [hobbit-project/platform#534]
### User story
As I user, I would like the empty KPIs from the Experiment Details page to be hidden. As a benchmark developer, I would like to be able to use numerous KPIs for my benchmark, but populate only a subset of the KPIs depending on the input parameters the user selected. Currently, all KPIs are shown by default, regardless of whether their value is set or not.

### Solution
When I go to the results page, i.e. the Experiment Details page, I want the empty (non-populated, not-used) KPIs simply hidden and not shown on the page.

**Comment by denkv** [comment]
Is there an example of such experiment on https://master.project-hobbit.eu/?

**Comment by denkv** [comment]
I have tried to remove the value of one of KPIs for an experiment on my local instance and the corresponding row disappeared from UI. Are you certain you're not populating the KPIs?
