### ISSUE TITLE
Add pagination for experiment results

### ISSUE THREAD

**Issue by yamalight** [hobbit-project/platform#54]
Currently the experiment results are displayed all at once (~3k entries on production server). 
That freezes browser for several second during processing, which is not very good.
Would be great to have pagination with configurable number of entries per page.

**Comment by MichaelRoeder** [comment]
Pagination has been added by @romankorf together with some other features making it much easier to work with the list of experiments (see the screenshot for the current state with some example data).

![newtable](https://user-images.githubusercontent.com/6122307/27911708-4c18ec18-625a-11e7-873f-effd69cc6661.png)
