### ISSUE TITLE
Evaluation storage crashes when ODIN benchmark uses 8 Data Generators

### ISSUE THREAD

**Issue by Kleanthi** [hobbit-project/platform#55]
Problem: all ODIN components terminate (apart from the controller that waits for the evaluation storage) and the benchmark proceeds in evaluation. The evaluation module of ODIN evaluates 3 SELECTqueries and waits for the rest of the tasks from the evaluation storage.
However, the storage crashes with:

May 17th 2017, 11:38:40.384		at java.lang.Thread.run(Thread.java:745)
	May 17th 2017, 11:38:40.382		at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:99)
	May 17th 2017, 11:38:40.382		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	May 17th 2017, 11:38:40.382		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	May 17th 2017, 11:38:40.381		at org.hobbit.evaluationstorage.RiakResultFuture.get(RiakResultFuture.java:34)
	May 17th 2017, 11:38:40.381		at org.hobbit.evaluationstorage.ResultPairIterator.next(ResultPairIterator.java:53)
	May 17th 2017, 11:38:40.381		at org.hobbit.core.components.AbstractEvaluationStorage$3.handleDelivery(AbstractEvaluationStorage.java:169)
	May 17th 2017, 11:38:40.381		at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:144)
	May 17th 2017, 11:38:40.381		at org.hobbit.evaluationstorage.RiakResultFuture.get(RiakResultFuture.java:68)
	May 17th 2017, 11:38:40.381		at org.hobbit.evaluationstorage.ResultPairIterator.next(ResultPairIterator.java:31)
	May 17th 2017, 11:38:40.380	java.lang.NullPointerException
	May 17th 2017, 11:38:40.380		at org.hobbit.evaluationstorage.RiakResultFuture.responseToResult(RiakResultFuture.java:59)

To re-produce the error, use default use value for each configurable parameter in ODIN benchmark and set number of Data generators - agents to 8.

**Comment by yamalight** [comment]
Should be fixed with https://github.com/hobbit-project/evaluation-storage/commit/3528c91e007015259c18b054eb511593ba233e7c, needs testing.

**Comment by yamalight** [comment]
Tested and working.
