### ISSUE TITLE
Doc slightly misleading without Keycloak

### ISSUE THREAD

**Issue by Saniamos** [hobbit-project/platform#565]
### Description
The documentation claims to use both volume and flag, but flag suffices due to https://github.com/hobbit-project/platform/blob/master/hobbit-gui/gui-serverbackend/configure-auth.sh

Additionally, the referenced file is not present in the config folder -> I presume the doc for volume is an artifact and the flag suffices. 

<img width="891" alt="Screenshot 2024-01-24 at 14 52 42" src="https://github.com/hobbit-project/platform/assets/13731087/6fd52f8b-75de-47e5-9982-7afb80b40b6e">

**Comment by Saniamos** [comment]
i'll try to create a pr soonish, need to finish smth else first

**Comment by MichaelRoeder** [comment]
Sorry for the inconveniences this may have caused. We updated the documentation accordingly.

**Comment by Saniamos** [comment]
haha, no worries! didn't take long to figure out, and the whole platform is running very nicely now. I'll drop you an email later :-)
