### ISSUE TITLE
Option for deactivating docker pull

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#6]
## Problem
At the moment, the platform always pulls images before creating containers. While this is reasonable for the "normal" usecase of the platform, it creates additional effort if a developer of a benchmark or a system is running the platform locally. In this case, the developer is forced to upload every new version since the Docker itself is not able to see that the locally build image is newer than the pulled image. It will only recognize that both images are different and pull the older image from the repository overriding the newer image.

## Solution
This should be solved by offering an environmental variable for the platform-controller to turn the pull off.

## Current workaround
If the developer deletes the image in the repository, the platform can not download an old version and is forced to use the local version.

**Comment by yamalight** [comment]
Done.
