### ISSUE TITLE
Challenge Tasks are deleted when editing them

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#62]
## Problem

During the configuration of a challenge, it is possible that challenge tasks ate deleted. This happened with a challenge containing 6 tasks. When editing/removing one of them, the platform removed 5 out of the 6 challenge tasks.

Reproduction of this error might be not easy since it is not clear until now which exact action caused this behaviour. For reproduction, a triple store should be used as backend to make sure that the UI behaves like in the real platform.

**Comment by Ennosigaeon** [comment]
@MichaelRoeder Can this issue be closed? That behaviour wasn't reported with the new UI.

**Comment by Ennosigaeon** [comment]
I close this issue, as this behaviour wasn't reported anymore and the UI was completely reworked since creation of this issue.
