### ISSUE TITLE
Reconfiguring challenge task can mix up registered systems

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#64]
## Problem

Give a challenge with at least two tasks and different systems registered for task 1 and 2, it is possible that if one of the two tasks is reconfigured and the benchmark of the other task is chosen (e.g., changing task 1 and choosing the same benchmark that is already used for task 2) (this might be done because of the workaround of #63), the task looses its registered systems and will have the same system registrations as the other task.

**Comment by Ennosigaeon** [comment]
@MichaelRoeder Can this issue be closed? That behaviour wasn't reported with the new UI.

**Comment by MichaelRoeder** [comment]
I couldn't reproduce the problem with the new UI. Seems to be fixed.
