### ISSUE TITLE
Parameter values in select boxes should be sorted

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#66]
## Problem

The values of parameters that can be chosen from a given set of values have a random order. 
![screen](https://user-images.githubusercontent.com/6122307/26965224-17a6bb9c-4cf5-11e7-91ab-ed251dc2fb0e.png)

They should be ordered alphabetically using their labels.

**Comment by Ennosigaeon** [comment]
Again, changes are available when #104 is merged.
