### ISSUE TITLE
Option to define max runtimes of experiments

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#7]
The platform should provide the possibility to
1. turn off the usage of a maximum runtime per experiments and
2. configure different maximum runtimes for different benchmarks

**Comment by yamalight** [comment]
1. globally defined timeout via env var
2. timeout per benchmark / challenge defined via mountable yaml file

timeout is currently applied here: https://github.com/hobbit-project/platform/blob/develop/platform-controller/src/main/java/org/hobbit/controller/ExperimentManager.java#L157

**Comment by yamalight** [comment]
Doesn't seem to be set for e.g. `http://w3id.org/bench#OdinBenchmark`
