### ISSUE TITLE
Challenge Task is not visible in the experiment details

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#71]
## Problem

On the bottom of the experiment overview, the list of challenge tasks can be found. Clicking on one of them, opens the details of the experiments that belong to the challenge (e.g., the results of MOCHA Task 4 can be found at http://master.project-hobbit.eu/#/experiments/details?challenge-task-id=http%3A%2F%2Fw3id.org%2Fhobbit%2Fchallenges%238bd4f77f-ec7c-4e73-8048-c986fbbdce7c_task3). However, in the experiment details, the challenge task fields are empty.

**Comment by romankorf** [comment]
Looks like the retrieval from the backend does not provide the challenge task name in this case. The Experiment JSON retrieved by the gui is missing the name. Only ID is provided

`[{
		"benchmark": {
			"description": "OKE 2015/16 Task 1 benchmark based on GERBIL",
			"id": "http://w3id.org/gerbil/hobbit/vocab#GerbilBenchmarkOKE2015T1",
...
		},
		"challengeTask": {
			"id": "http://w3id.org/hobbit/challenges#686d2848-e4c3-4cf4-a991-243857fceb7f_task1"
		},
...		}
	}, ...`

**Comment by romankorf** [comment]
The issue only appears when selecting a challenge task at the bottom of the experiment list view. When selecting the experiments of a challenge task individually this does not happen. The calls are calling the same web-service with different parameter. The first provides the challenge task id, the second case provides a list of experiment ids.

http://master.project-hobbit.eu/#/experiments/details?challenge-task-id=http%3A%2F%2Fw3id.org%2Fhobbit%2Fchallenges%238bd4f77f-ec7c-4e73-8048-c986fbbdce7c_task3

vs 

http://master.project-hobbit.eu/#/experiments/details?id=1495629645602%2C1495629645583%2C1495629645579%2C1495629645571

**Comment by MichaelRoeder** [comment]
The issue can be fixed by extending the SPARQL query used to gather the experiments for a given challenge task to also gather the triples of this challenge task (which is already implemented for retrieving experiment triples).

From https://github.com/hobbit-project/core/commit/72ff1cf90b989f605e7e6579e38d63b6025e1389 on, the change is part of the core library.
