### ISSUE TITLE
GUI should display some "not found" message when backend says so

### ISSUE THREAD

**Issue by denkv** [hobbit-project/platform#79]
Currently just an invisible script error happens.

**Comment by Ennosigaeon** [comment]
While handling #104, I have done some improvements concerning  non-existing data.

### General
Every unknown URL is redirected to a not-found page.

### Benchmarks
Benchmarks shows a warning if no benchmarks are found

### Challenges
Overview page shows a warning if no challenges are found. Challenge experiments and systems show 'No records found '.

If `http://localhost:4200/challenges/:id` is opened with a non-existing id, the gui-backend returns 204 (NO_CONTENT). According to specification 204 indicates 
> The server has successfully fulfilled the request and that there is no additional content to send in the response payload body.
It would be correct to use 404 (RESOURCE_NOT_FOUND) resulting in an error page.

If `http://localhost:4200/challenges/:id/task/:task` is opened with a non-existing task, an error page is displayed.

### Experiments
When viewing the details of a non-existing experiment, an error message is displayed. When viewing the details of a non-existing challegen, error page is displayed.

This issue will be closed when #104 is resolved and merged.

**Comment by Ennosigaeon** [comment]
I just noticed, that the wrong response code is addressed in #78
