### ISSUE TITLE
Use normal paths in GUI instead of hash/fragment

### ISSUE THREAD

**Issue by denkv** [hobbit-project/platform#81]
Are there any problems with such a change?

That's how it can be done: https://github.com/hobbit-project/platform/compare/develop...feature/path-routing

For better implementation, it would probably be better to specify catch-all address for that if possible.

**Comment by MichaelRoeder** [comment]
@romankorf do you see any drawbacks of such a change? If it breaks the GUI or introduces major drawbacks in the work of angular, we should avoid the change.

**Comment by romankorf** [comment]
Usually this should work. However, we only did a few tests with this configuration. So we do not know if there is some situation, where there might be an issue.

**Comment by denkv** [comment]
Added redirects to handle old URLs.

**Comment by denkv** [comment]
Done.
