### ISSUE TITLE
Missing w3id.org URLs

### ISSUE THREAD

**Issue by denkv** [hobbit-project/platform#82]
Some URLs are used in HOBBIT, but [corresponding redirects at w3id.org](https://github.com/MichaelRoeder/w3id.org/blob/master/hobbit/.htaccess) are not configured:

`http://w3id.org/hobbit/platform-benchmark/vocab`

**Comment by MichaelRoeder** [comment]
Yes, the observation is absolutly correct. However, we won't have the resource to write ontologies for all the predicates that are used by our benchmarks (especially, if it is an internal benchmark like the platform-benchmark).

The forwarding should focus on the important URI types which are already forwarded in the linked `.htaccess` file.
