### ISSUE TITLE
Leaderboard for open challenges

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#83]
## Feature description

For every task of an open challenge, there has to be a leaderboard listing the participants of the challenge task and their results. We assume that there is a "main KPI" which can be used to sort the participants.
* [UI] Next to the tasks of an open challenge, there should be a link to the leadboard page
* [UI] It has to be possible to have a direct link to a leadboard
* [UI] For the table of the leaderboard, the features of the experiment list should be reused, i.e.,
    * Sortability of rows in the table
    * Filtering by given value
    * Select one or several experiments and see its details
    * Instead of the experiment ID, the first column (the first column after the checkbox column) should contain the rank of the participants. The table should by default be sorted ascending regarding this column.
* [UI-backend] The table should contain the best results per participating system according to the main KPI.
* [Ontology] The owner of the challenge needs a property to express which KPI is the "main KPI".

**Comment by denkv** [comment]
- Challenge (or task) should contain a new boolean property to control the visibility of leaderboard.

**Comment by MichaelRoeder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[HOBBIT] Open Challenges](https://trello.com/c/0KQKy0XE/398-hobbit-open-challenges)
