### ISSUE TITLE
Existing experiment is not listed in the list of results

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#86]
## Problem

On our online instance, I executed an experiment with the id `1502710813567`. It terminated and the insertion into the triple store was successful:
```
August 14th 2017, 23:19:46.655	git.project-hobbit.eu:4567/gitadmin/platform-controller-image	2017-08-14 21:19:46,646 INFO [org.hobbit.controller.PlatformController] - <received command: session=1502710813567, command=BENCHMARK_FINISHED_SIGNAL>
August 14th 2017, 23:20:04.565	git.project-hobbit.eu:4567/gitadmin/platform-controller-image	2017-08-14 21:20:04,566 INFO [org.hobbit.controller.ExperimentManager] - <Benchmark terminated. Experiment 1502710813567 has been finished. Removing it from the queue and setting the config to null.>
August 14th 2017, 23:20:04.596	git.project-hobbit.eu:4567/gitadmin/platform-storage-image	2017-08-14 21:20:04,597 INFO [org.hobbit.storage.service.StorageService] - <Received a request to call the SPARQL Endpoint at http://vos:8890/sparql-auth and execute the following query: ... INSERT {   ... >
August 14th 2017, 23:20:04.645	git.project-hobbit.eu:4567/gitadmin/platform-storage-image	[Storage Service] Done with the SPARQL UPDATE.
```
(Log messages of Insertion can be found at https://log.project-hobbit.eu/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-14T21:19:57.115Z',mode:absolute,to:'2017-08-14T21:21:00.275Z'))&_a=(columns:!(image_name,message),index:'logstash-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'%22git.project-hobbit.eu:4567%2Fgitadmin%2Fplatform-storage-image%22')),sort:!('@timestamp',desc)) )

However, it does not appear in the list of experiment results, where it should be listed as the first experiment in screenshot 1
![notlisted1](https://user-images.githubusercontent.com/6122307/29310087-b869f9f4-81ac-11e7-89db-ead86195aefb.png)

and as the only experiment in screenshot 2.
![notlisted2](https://user-images.githubusercontent.com/6122307/29310095-c089111a-81ac-11e7-9b1e-5edf541360c2.png)

The URL http://master.project-hobbit.eu/#/experiments/details?id=1502710813567 is not working as well while the data can be queried from the public SPARQL endpoint: https://db.project-hobbit.eu/sparql?default-graph-uri=&query=PREFIX+hobbit%3A+%3Chttp%3A%2F%2Fw3id.org%2Fhobbit%2Fvocab%23%3E++%0D%0A%0D%0ACONSTRUCT+%7B+++++%3Chttp%3A%2F%2Fw3id.org%2Fhobbit%2Fexperiments%231502710813567%3E+a+hobbit%3AExperiment+.%0D%0A+++++%3Chttp%3A%2F%2Fw3id.org%2Fhobbit%2Fexperiments%231502710813567%3E+hobbit%3AinvolvesSystemInstance+%3Fsystem+.%0D%0A+++++%3Chttp%3A%2F%2Fw3id.org%2Fhobbit%2Fexperiments%231502710813567%3E+hobbit%3AinvolvesBenchmark+%3Fbenchmark+.%0D%0A+++++%3Chttp%3A%2F%2Fw3id.org%2Fhobbit%2Fexperiments%231502710813567%3E+%3FexperimentProp%09%3FexperimentObj+.%0D%0A+++++%3Chttp%3A%2F%2Fw3id.org%2Fhobbit%2Fexperiments%231502710813567%3E+hobbit%3AisPartOf+%3FchallengeTask+.%0D%0A+++++%3FchallengeTask+%3FchallengeTaskProp+%3FchallengeTaskObject+.%0D%0A+++++%3Chttp%3A%2F%2Fw3id.org%2Fhobbit%2Fexperiments%231502710813567%3E+%3FresultProp+%3FresultValue+.%0D%0A+++++%3FresultProp+a+hobbit%3AKPI+.%0D%0A+++++%3FresultProp+%3FresultPropProp+%3FresultPropObject+.%0D%0A+++++%3Chttp%3A%2F%2Fw3id.org%2Fhobbit%2Fexperiments%231502710813567%3E+%3FparameterProp+%3FparameterValue+.%0D%0A+++++%3FparameterProp+a+%3FparameterType+.%0D%0A+++++%3FparameterProp+%3FparameterPropProp+%3FparameterPropObject+.%0D%0A+++++%3Fbenchmark+%3FbenchmarkProp+%3FbenchmarkObject+.%0D%0A+++++%3Fsystem+%3FsystemProp+%3FsystemObject+.%0D%0A+%7D+WHERE+%7B+++++%7B+++++++++GRAPH+%3Fv1+%7B+++++++++++++%3Chttp%3A%2F%2Fw3id.org%2Fhobbit%2Fexperiments%231502710813567%3E+a+hobbit%3AExperiment+.%0D%0A+++%09++++++++%3Chttp%3A%2F%2Fw3id.org%2Fhobbit%2Fexperiments%231502710813567%3E+%3FexperimentProp+%3FexperimentObj+.%0D%0A+++%09++++%7D+++++%7D+++++UNION+++++%7B+++++++++GRAPH+%3Fv1+%7B+++++++++++++%3Chttp%3A%2F%2Fw3id.org%2Fhobbit%2Fexperiments%231502710813567%3E+a+hobbit%3AExperiment+.%0D%0A+++%09++++++++%3Chttp%3A%2F%2Fw3id.org%2Fhobbit%2Fexperiments%231502710813567%3E+hobbit%3AinvolvesSystemInstance+%3Fsystem+.%0D%0A+++%09++++++++OPTIONAL+%7B+%3Fsystem+%3FsystemProp+%3FsystemObject+.%0D%0A+%7D+++%09++++%7D+++++%7D+++++UNION+++++%7B+++++++++GRAPH+%3Fv1+%7B+++++++++++++%3Chttp%3A%2F%2Fw3id.org%2Fhobbit%2Fexperiments%231502710813567%3E+a+hobbit%3AExperiment+.%0D%0A+++%09++++++++%3Chttp%3A%2F%2Fw3id.org%2Fhobbit%2Fexperiments%231502710813567%3E+hobbit%3AinvolvesBenchmark+%3Fbenchmark+.%0D%0A+++%09++++++++OPTIONAL+%7B+%3Fbenchmark+%3FbenchmarkProp+%3FbenchmarkObject+.%0D%0A+%7D+++%09++++%7D+++++%7D+++++UNION+++++%7B+++++++++GRAPH+%3Fv1+%7B+++++++++++++%3Chttp%3A%2F%2Fw3id.org%2Fhobbit%2Fexperiments%231502710813567%3E+a+hobbit%3AExperiment+.%0D%0A+++++++++++++%3Chttp%3A%2F%2Fw3id.org%2Fhobbit%2Fexperiments%231502710813567%3E+hobbit%3AisPartOf+%3FchallengeTask+.%0D%0A+++++++++++++%3FchallengeTask+%3FchallengeTaskProp+%3FchallengeTaskObject+.%0D%0A+++%09++++%7D+++++%7D+++++UNION+++++%7B+++++++++GRAPH+%3Fv1+%7B+++++++++++++%3Chttp%3A%2F%2Fw3id.org%2Fhobbit%2Fexperiments%231502710813567%3E+a+hobbit%3AExperiment+.%0D%0A+++++++++++++%3Chttp%3A%2F%2Fw3id.org%2Fhobbit%2Fexperiments%231502710813567%3E+%3FresultProp+%3FresultValue+.%0D%0A+++%09++++++++%3Chttp%3A%2F%2Fw3id.org%2Fhobbit%2Fexperiments%231502710813567%3E+hobbit%3AinvolvesBenchmark+%3Fbenchmark+.%0D%0A+++++++++++++%3Fbenchmark+hobbit%3AmeasuresKPI+%3FresultProp+.%0D%0A+++++++++++++%3FresultProp+a+hobbit%3AKPI+.%0D%0A+++++++++++++OPTIONAL+%7B+%3FresultProp+%3FresultPropProp+%3FresultPropObject+.%0D%0A+%7D+++%09++++%7D+++++%7D+++++UNION+++++%7B+++++++++GRAPH+%3Fv1+%7B+++++++++++++%3Chttp%3A%2F%2Fw3id.org%2Fhobbit%2Fexperiments%231502710813567%3E+a+hobbit%3AExperiment+.%0D%0A+++%09++++++++%3Chttp%3A%2F%2Fw3id.org%2Fhobbit%2Fexperiments%231502710813567%3E+hobbit%3AinvolvesBenchmark+%3Fbenchmark+.%0D%0A+++++++++++++%3Fbenchmark+hobbit%3AhasParameter+%3FparameterProp+.%0D%0A+++++++++++++%3Chttp%3A%2F%2Fw3id.org%2Fhobbit%2Fexperiments%231502710813567%3E+%3FparameterProp+%3FparameterValue+.%0D%0A+++++++++++++%3FparameterProp+a+%3FparameterType+.%0D%0A+++++++++++++%7B%3FparameterProp+a+hobbit%3AParameter%7D+UNION+%7B%3FparameterProp+a+hobbit%3AConfigurableParameter%7D+UNION+%7B%3FparameterProp+a+hobbit%3AFeatureParameter%7D.+++++++++++++OPTIONAL+%7B+%3FparameterProp+%3FparameterPropProp+%3FparameterPropObject+.%0D%0A+%7D+++++++++%7D+++++%7D+%7D&format=text%2Fturtle&timeout=0&debug=on

**Comment by denkv** [comment]
Looks like now experiment can be found in the list and the experiment details page works for it as well.
