### ISSUE TITLE
Internal queue security

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#89]
## Description

Add the security of the internal queues as described in [D2.1](https://project-hobbit.eu/wp-content/uploads/2016/11/D2.1_Detailed_Architecture_of_the_HOBBIT_Platform.pdf).
* Check whether giving a secure name to a queue is sufficient or whether additional security features are needed.

**Comment by earthquakesan** [comment]
@MichaelRoeder this issue affects platform-storage and core modules

**Comment by earthquakesan** [comment]
@MichaelRoeder travis can not find new core version, how can I update it?
