### ISSUE TITLE
Platform controller always uses our Gitlab

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#9]
The platform controller always uses our online gitlab. There is no way for a developer to test his benchmark or system without uploading it.

It would be better if we could have a second way to retrieve the `*.ttl` meta data files, e.g., a local directory in which a developer could place the files. This would enable the usage of the platform even for people who are not allowed to upload their images to our platform.

**Comment by denkv** [comment]
A simple to implement (but maybe not to use) would be a provided configuration for running local gitlab container.

**Comment by MichaelRoeder** [comment]
That is not necessary. I already started to implement a file-based repo: https://github.com/hobbit-project/platform/blob/master/platform-controller/src/main/java/org/hobbit/controller/docker/FileBasedImageManager.java
We just have to finish its implementation :wink:
