### ISSUE TITLE
Support regularly executable challenges

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#92]
## Description

For the open challenges, we need a challenge that is regularly executable instead of only once. It should be possible to define challenges that 
* are executed every `x` days 
* by creating experiments for all systems registered since the last execution
* until a final date `y` is reached. (optional)

* The first step would be to implement the support of this in the platform controller and to define the properties to express this additional information in RDF.
* The second step is the support of the configuration of this in the GUI (optional, might be skipped)

**Comment by denkv** [comment]
>creating experiments for all systems registered since the last execution

So systems registered before last challenge execution are excluded there? Each system will have only one experiment per challenge this way.

**Comment by MichaelRoeder** [comment]
Yes, you are right. But this is not the behaviour that we need. I am thinking of the following workaround:

We have three graphs, in which information are stored: `public`, `private` and `challengeDefs`. Until now, the registration is stored in `challengeDefs`, the results of the experiments are stored in `private` and when they are published, all information is moved from `challengeDefs` and `private` to `public`.

We could adapt this for repeatable challenges to the following workflow:
1. when an experiment including `ex:SystemA` is executed for this challenge, we directly publish it, i.e., copy the challenge information from the challenge def to the public graph including the triple
```
ex:MyChallengeTask    hobbit:involvesSystemInstance    ex:SystemA .
```
Now, we could add the same triple again in the challengeDef graph to indicate, that we want to execute the challenge again with this system.

However, this workaround is a little bit dirty since we won't be able to define re-executable challenges that are not publishing their results directly after the experiment execution.

An alternative to this would be to introduce a new property, e.g., `involvedSystemInstance`, wich is used for documenting that a system has been involved while `involvesSystemInstance` would be used to express that the system will be involved in the next run. At the moment, `involvesSystemInstance` is used for both.

**Comment by MichaelRoeder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[HOBBIT] Open Challenges](https://trello.com/c/0KQKy0XE/398-hobbit-open-challenges)

**Comment by MichaelRoeder** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[HOBBIT] Open Challenges](https://trello.com/c/0KQKy0XE/398-hobbit-open-challenges)
