### ISSUE TITLE
Regular clearing of Docker daemon

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#94]
## Description

At the moment, the platform is pulling images but does not take care of freeing disk space. This leads to Problems like
```
Exception in thread "main" java.io.IOException: No space left on device
```
The disk space can be freed manually using
```
sudo docker rmi $(sudo docker images -f "dangling=true" -q)
```
However, an automatic removing of unused images would be much better. This could be done after pulling a new image. The platform could check whether after the pull has been completed, old images with the same name but without a version tag are available. These images could be removed by the platform.

Note that the implementation of this issue might be influenced by the implementation of #96.

**Comment by denkv** [comment]
(As discussed) we can set up nodes for periodic cleanup by local means on each node, or make a docker image with cleanup job and run it as a global swarm service with docker socket mounted.
