### ISSUE TITLE
Cluster health checks

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#97]
## Description

The platform controller has to be able to observe the status of the cluster that is used to execute the
experiments. If one of the nodes drops out of the cluster, the comparability between single experiments
is not given. Thus, the platform controller needs to be aware of the number of working nodes that
are available for the experiment. It uses the Docker Swarm API to check the availability of the single
nodes.

* Implement a way to define the number of nodes the platform should expect to be in the cluster.
* Regularly ask the docker swarm for its nodes (e.g., using a `docker info` equivalent).
    * before an experiment is started to decide whether it should be started or postponed
    * after an experiment has ended. If a node drops out during the experiment, an error could be added ot the result module.

**Comment by earthquakesan** [comment]
Implemented in #219
