### ISSUE TITLE
Support gathering of resource usage

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#98]
## Description

Some benchmarks need to measure the resources used by the system, e.g., disk space or CPU time. The platform should support that by offering these stats to a benchmark (if the benchmark requested this information).

* A benchmark has to request the information from the platform controller (since the benchmark itself is not allowed to directly communicate with the Docker daemon).
    1. The benchmark controller sends a request to the platform controller, e.g., `REQUEST_SYSTEM_RESOURCES_USAGE`.
    1. The platform controller 
        1. Gets a list of system containers
        1. Collects the stats for every container
        1. Answers with a list of simple java objects serialized as JSON containing
            * CPU usage
            * Memory usage
            * Disk usage
* The statistics are gathered by a thread of the platform controller using
    * the Docker container API for CPU and memory usage https://docs.docker.com/engine/api/v1.30/#operation/ContainerStats
        * It needs to be checked that this is supported by Docker swarm and the Java Docker client
    * the Docker API for disk space usage of containers and volumes https://docs.docker.com/engine/api/v1.30/#operation/SystemDataUsage 
        * It needs to be checked that this is supported by Docker swarm and the Java Docker client

## Discussion
* :heavy_check_mark: ~~This assumes that `df` is supported by *all* system containers.~~ We will use container list of the API
* :information_source: For stream reasoning, there is a framework that should already have this feature AFAIK https://github.com/streamreasoning/heaven
* Should we have a stop command as well or should the monitoring thread terminate itself when all system containers are terminated?
* Which part of the benchmark should be responsible for storing the statistics? (most probably they will be needed during the evaluation and not before) The evaluation storage seems to be the first choice. However, how should the evluation module access this data?
* We should draft a JSON/Java class that is used to store/submit the data. Should we have two of them since we can not gather CPU/Memory usage as well as disk space at the same time?

**Comment by yamalight** [comment]
Looks like you can pass `size: true` to [container list](https://docs.docker.com/engine/api/v1.30/#tag/Container) method to get space usage for all containers.

**Comment by MichaelRoeder** [comment]
Nice :smiley: 
I updated the discription above and added new questions.

**Comment by yamalight** [comment]
@MichaelRoeder note that method above needs to be tested to see how it handles volumes. You might need to manually get size of container and size of volumes and add them up (or just display both).

**Comment by MichaelRoeder** [comment]
That is true. So implementing #95 might increase the complexity of this issue.

However, neither the [list volume](https://docs.docker.com/engine/api/v1.30/#operation/VolumeList) nor the [inspect volume](https://docs.docker.com/engine/api/v1.30/#operation/VolumeInspect) commands of the API seem to return information about volume sizes. I would assume that the volume sizes are added to the container size - although I totally agree that we need to check this. I added this point to the points above.

**Comment by yamalight** [comment]
@MichaelRoeder found even better thing - there's [SystemDataUsage](https://docs.docker.com/engine/api/v1.30/#operation/SystemDataUsage) API endpoint that gives sizes for all entities.

**Comment by MichaelRoeder** [comment]
:+1: 
Updated the description accordingly.

**Comment by Aklakan** [comment]
A Java library which reads does more or less a `lshw` in a platform independent way and supports JSON output is OSHI:

https://github.com/oshi/oshi

**Comment by MichaelRoeder** [comment]
Updated the description after a discussion with @vpapako

**Comment by denkv** [comment]
There doesn't seem simple alternative to container stats API for containers on other swarm node. We can try a solution with additional service for gathering stats in swarm, like this: https://medium.com/@soumyadipde/monitoring-in-docker-stacks-its-that-easy-with-prometheus-5d71c1042443

**Comment by MichaelRoeder** [comment]
I already implemented the feature and added a simple class for checking it manually (https://github.com/hobbit-project/platform/blob/feature%2Fresource-usage-98/platform-controller/src/main/java/org/hobbit/controller/test/RequestSystemResources.java).

The only problem that is left is that I am not sure about the measuring units that are used. I think CPU time could be in Milliseconds. But what about RAM and disk space. Are they counted in bytes? And if this is the case, shouldn't we count the disk space in kB or MB since we are summing the spaces of the single containers up to one large sum which might overflow the `long` datatype...? :thinking:
